In [1]:
import linear, numpy as np

# Recitation
Find the basis and dimension for each of 4 subspaces of r.  
column space 2 = pivot columns of r1  
$\begin{bmatrix} 5 & 0 \\ 10 & 1 \\ -5 & 0 \end{bmatrix}$  
null space 1 = free columns of r2 + identity  
$\begin{bmatrix} -0.6 \\ -1 \\ 1 \end{bmatrix}$  
row space 2 = pivot rows of r2  
$\begin{bmatrix} 1 & 0 & 0.6 \\ 0 & 1 & 1 \end{bmatrix}$  
left null space 1 = free rows of r1.I  
$\begin{bmatrix} 1 & 0 & 1 \end{bmatrix}$  

In [2]:
r1 = np.array([
    [1,0,0],
    [2,1,0],
    [-1,0,1],
])
r2 = np.array([
    [5,0,3],
    [0,1,1],
    [0,0,0],
])
_ = linear.rrefIdentity(r1 @ r2)

Bottom half
[[  5.   0.   3.   1.   0.   0.]
 [ 10.   1.   7.   0.   1.   0.]
 [ -5.   0.  -3.   0.   0.   1.]]
[[ 5.  0.  3.  1.  0.  0.]
 [ 0.  1.  1. -2.  1.  0.]
 [ 0.  0.  0.  1.  0.  1.]]
Divide
[[ 1.   0.   0.6  0.2  0.   0. ]
 [ 0.   1.   1.  -2.   1.   0. ]
 [ 0.   0.   0.   1.   0.   1. ]]
Top Half
[[ 1.   0.   0.6  0.   0.  -0.2]
 [ 0.   1.   1.   0.   1.   2. ]
 [ 0.   0.   0.   1.   0.   1. ]]


# Problem Set
## 1
A is an m by n matrix of rank r. Suppose there are right sides b for which Ax = b has
no solution.  
a) What are all the inequalities (< or ≤) that must be true between m, n,
and r?  
r < m  
b) How do you know that ATy = 0 has solutions other than y = 0?  
Because r < m => there are free rows  
## 2
A.T @ y = d is solvable when d is in which of the
four subspaces?  
Row space  
The solution y is unique when which subspace contains
only the zero vector?  
left nullspace  