In [1]:
import linear, numpy as np

# Recitation
Show that the set of 2x3 matrices whose nullspace contains  
$ \begin{bmatrix} 2 \\ 1 \\ 1 \end{bmatrix} $  
is a vector subspace and find a basis for it.  
$ \begin{bmatrix} 1 & 0 & -2 \\ 0 & 1 & -1 \end{bmatrix} $  
If A @ nullspace = 0 and B @ nullspace = 0, (A+B) @ nullspace = A @ nullspace + B @ nullspace = 0 + 0, therefore addition works.  
CA @ nullspace = C(A @ nullspace), therefore multiplication works.  
What about the set of those whose column space contains  
$ \begin{bmatrix} 2 \\ 1 \end{bmatrix} $  
No because 0 matrix is not in the set.  
# Problem Set
## 1
Write the 3 by 3 identity matrix as a combination of the other five permutation
matrices. Then show that those five matrices are linearly independent.
(Assume a combination gives c1P1 + · · · + c5P5 = 0 and check
entries to prove ci is zero.) The five permutation matrices are a basis for the
subspace of three by three matrices with row and column sums all equal.  
  
Stuck

Sum of 5 matrices =  
$ \begin{bmatrix} c1 & c2 + c3 & c4 + c5 \\ c2 + c4 & c5 & c1 + c3 \\ c3 + c5 & c1 + c4 & c2 \end{bmatrix} $  
For sum to = 0, c1, c2, c5 must equal 0. c2, c4, c3 = 0 - c1 = 0

In [2]:
permutations = [np.identity(3)[[a,b,c],:] for a in range(3) for b in range(3) for c in range(3) 
if b != a and c != a and c != b and [a,b,c] != [0,1,2]]
for p in permutations:
    print(p)
    print()

[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]

[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]

[[ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]

[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]]



## 2
M is the space of three by three matrices. Multiply
each matrix X in M by A  
a) Which matrices X lead to AX = 0?  
Each column of X must be a multiple of 1,1,1  
b) Which matrices have the form AX for some matrix X?  
Each column of AX must be a combination of columns of A. Since all columns of A sum to 0, columns of AX must also sum to 0  
c) Part (a) finds the “nullspace” of the operation AX and part (b) finds
the “column space.” What are the dimensions of those two subspaces
of M? Why do the dimensions add to (n − r) + r = 9?  
nullspace is  dimension, column space is 

In [3]:
A = np.array([
    [1,0,-1],
    [-1,1,0],
    [0,-1,1],
])
_ = linear.rref(A)

Bottom half
[[ 1.  0. -1.]
 [-1.  1.  0.]
 [ 0. -1.  1.]]
[[ 1.  0. -1.]
 [ 0.  1. -1.]
 [ 0. -1.  1.]]
[[ 1.  0. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]]
Divide
Top Half
