In [1]:
import linear, numpy as np

# Recitation
Find N(A), N(A.T)  
N(A) = [1,1,1,1,1]  
Answer: Calculate N(A) by using Ax = differences between x's  
N(A.T)  
Answer: Calculate solutions where loops sum to 0, and other edges are 0  

In [2]:
Ar = np.array([
    [-1,1,0,0,0],
    [0,-1,1,0,0],
    [-1,0,1,0,0],
    [0,-1,0,1,0],
    [0,0,0,-1,1],
    [0,0,1,0,-1],
])
# Find N(A), N(A.T)
_ = linear.rrefIdentity(Ar)
# _ = linear.rref(Ar)
# Trace A.T @ A
nat = np.array([
    # From elimination
    [0, 1, 0, -1, -1, -1],
    [1, 0, -1, 1, 1, 1],
    # From loops
    [1,1,-1,0,0,0],
    [0,1,0,-1,-1,-1],
])
print(nat @ Ar)
_ = linear.rref(nat)

Bottom half
[[-1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.  0.  1.  0.  0.  0.  0.]
 [-1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0. -1.  0.  1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0. -1.  0.  0.  0.  0.  0.  1.]]
[[-1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0. -1.  0.  1.  0.  0.  0.]
 [ 0. -1.  0.  1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0. -1.  0.  0.  0.  0.  0.  1.]]
[[-1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1. -1.  1.  0.  0.  0.]
 [ 0.  0. -1.  1.  0.  0. -1.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0. -1.  0.  0.  0.  0.  0.  1.]]
[[-1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0.  0. -1.  0.  1.  0.  0.

# Problem Set
## 1
Write down
the four by four incidence matrix A for the square graph, shown below.  
$\begin{bmatrix} -1 & 1 & 0 & 0 \\ 0 & -1 & 1 & 0 \\ 0 & 0 & 1 & -1 \\ -1 & 0 & 0 & 1 \end{bmatrix}$  
(Hint: the first row has -1 in column 1 and +1 in column 2.)  
What vectors (x1, x2, x3, x4) are in the nullspace of A?  
$\begin{bmatrix} x2 - x1 \\ x3 - x2 \\ x3 - x4 \\ x4 - x1 \end{bmatrix}$  
$\begin{bmatrix} 1 \\ 1 \\ 1 \\ 1 \end{bmatrix}$  
How do you know that (1,0,0,0) is
not in the row space of A? 

## 2
Continuing with the network from problem one,
suppose the conductance matrix is  
$\begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 2 & 0 & 0 \\ 0 & 0 & 2 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$  
Multiply matrices to find A.T @ C @ A. For f = (1, 0, −1, 0), find a solution to
A.T @ C @ A @ x = f.  
Write the potentials x and currents y = −CAx on the square
graph (see above) for this current source f going into node 1 and out from
node 3.  
A = 5 edges by 4 nodes  
x = 4 node potentials  
Ax = 5 potential differences  
C = 5 by 5 conductances  
y = CAx = 5 edge currents  
A.T = 4 nodes by 5 edges  

In [3]:
A = np.array([
    [-1,1,0,0],
    [0,-1,1,0],
    [0,0,1,-1],
    [-1,0,0,1],
])
C = np.array([
    [1,0,0,0],
    [0,2,0,0],
    [0,0,2,0],
    [0,0,0,1],
])
# Find x
f = np.array([[1,0,-1,0]]).T
_ = linear.rrefAugmented(A.T @ C @ A, f)
x = np.array([0.5, 0, -0.25, 0])
print(A.T @ C @ A @ x)
# Find y
print(-C @ A @ x)

Bottom half
[[ 2. -1.  0. -1.  1.]
 [-1.  3. -2.  0.  0.]
 [ 0. -2.  4. -2. -1.]
 [-1.  0. -2.  3.  0.]]
[[ 2.  -1.   0.  -1.   1. ]
 [ 0.   2.5 -2.  -0.5  0.5]
 [ 0.  -2.   4.  -2.  -1. ]
 [ 0.  -0.5 -2.   2.5  0.5]]
[[ 2.  -1.   0.  -1.   1. ]
 [ 0.   2.5 -2.  -0.5  0.5]
 [ 0.   0.   2.4 -2.4 -0.6]
 [ 0.   0.  -2.4  2.4  0.6]]
[[ 2.  -1.   0.  -1.   1. ]
 [ 0.   2.5 -2.  -0.5  0.5]
 [ 0.   0.   2.4 -2.4 -0.6]
 [ 0.   0.   0.   0.   0. ]]
Divide
[[ 1.   -0.5   0.   -0.5   0.5 ]
 [ 0.    1.   -0.8  -0.2   0.2 ]
 [ 0.    0.    1.   -1.   -0.25]
 [ 0.    0.    0.    0.    0.  ]]
Top Half
[[ 1.   -0.5   0.   -0.5   0.5 ]
 [ 0.    1.    0.   -1.    0.  ]
 [ 0.    0.    1.   -1.   -0.25]
 [ 0.    0.    0.    0.    0.  ]]
[[ 1.    0.    0.   -1.    0.5 ]
 [ 0.    1.    0.   -1.    0.  ]
 [ 0.    0.    1.   -1.   -0.25]
 [ 0.    0.    0.    0.    0.  ]]
[ 1.  0. -1.  0.]
[ 0.5  0.5  0.5  0.5]
