In [1]:
import linear, numpy as np

# Recitation
A =  
$ \begin{bmatrix} 1 & 1 & 1 \\ 1 & 2 & 3 \\ 3 & 4 & k \end{bmatrix} $  
For which k does Ax = [2,3,7]
Have a unique solution?  
k != 5  
B. Which k - infinitely many solutions?  
k = 5, because row space is no longer independent  
C. When k = 4, find LU decomposition  
L = $ \begin{bmatrix} 1 & 0 & 0 \\ 1 & 1 & 0 \\ 3 & 1 & 1 \end{bmatrix} $
U = $ \begin{bmatrix} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & -1 \end{bmatrix} $  
D. For all k, find complete solutions  
Xn is origin because matrix is full rank.  
Xp = [1,1,0]  
For k = 5, Xn = [1, -2, 1]

In [2]:
A = linear.toMatrix('$ \begin{bmatrix} 1 & 1 & 1 \\ 1 & 2 & 3 \\ 3 & 4 & 5 \end{bmatrix} $')
output = linear.rrefAugmented(A, np.array([[2,3,7]]).T)
# print(linear.toTex(output[2])) # 
# print(linear.toTex(output[5]))
L = linear.toMatrix('$ \begin{bmatrix} 1 & 0 & 0 \\ 1 & 1 & 0 \\ 3 & 1 & 1 \end{bmatrix} $')
print(L @ output[2])

Bottom half
[[ 1.  1.  1.  2.]
 [ 1.  2.  3.  3.]
 [ 3.  4.  5.  7.]]
[[ 1.  1.  1.  2.]
 [ 0.  1.  2.  1.]
 [ 0.  1.  2.  1.]]
[[ 1.  1.  1.  2.]
 [ 0.  1.  2.  1.]
 [ 0.  0.  0.  0.]]
Divide
Top Half
[[ 1.  0. -1.  1.]
 [ 0.  1.  2.  1.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  2.]
 [ 1.  2.  3.  3.]
 [ 3.  4.  5.  7.]]
