In [1]:
import pandas as pd, linear, numpy as np
filename = '2 Elimination with Matrices.xlsx'

# Recitation

In [2]:
data = linear.separate(filename, 'Recitation', 4)
print(data)

[matrix([[ 1., -1., -1.,  1.,  0.],
        [ 2.,  0.,  2.,  0.,  8.],
        [ 0., -1., -2.,  0., -8.],
        [ 3., -3., -2.,  4.,  7.]])]


In [3]:
outputR = linear.rref(data[0]*2)

Bottom half
[[  2.  -2.  -2.   2.   0.]
 [  4.   0.   4.   0.  16.]
 [  0.  -2.  -4.   0. -16.]
 [  6.  -6.  -4.   8.  14.]]
[[  2.  -2.  -2.   2.   0.]
 [  0.   4.   8.  -4.  16.]
 [  0.  -2.  -4.   0. -16.]
 [  0.   0.   2.   2.  14.]]
[[  2.  -2.  -2.   2.   0.]
 [  0.   4.   8.  -4.  16.]
 [  0.   0.   0.  -2.  -8.]
 [  0.   0.   2.   2.  14.]]
[[  2.  -2.  -2.   2.   0.]
 [  0.   4.   8.  -4.  16.]
 [  0.   0.   2.   2.  14.]
 [  0.   0.   0.  -2.  -8.]]
Divide
[[ 1. -1. -1.  1.  0.]
 [ 0.  1.  2. -1.  4.]
 [ 0.  0.  1.  1.  7.]
 [-0. -0. -0.  1.  4.]]
Top Half
[[ 1. -1. -1.  0. -4.]
 [ 0.  1.  2.  0.  8.]
 [ 0.  0.  1.  0.  3.]
 [-0. -0. -0.  1.  4.]]
[[ 1. -1.  0.  0. -1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0.  3.]
 [-0. -0. -0.  1.  4.]]
[[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0.  3.]
 [-0. -0. -0.  1.  4.]]


# Problem 1

In [4]:
data1 = linear.separate(filename, '1', 2)
print(data1)

[matrix([[  2.,   3.,   5.],
        [  6.,  15.,  12.]])]


In [5]:
output1 = linear.rref(data1[0])

Bottom half
[[  2.   3.   5.]
 [  6.  15.  12.]]
[[ 2.  3.  5.]
 [ 0.  6. -3.]]
Divide
[[ 1.   1.5  2.5]
 [ 0.   1.  -0.5]]
Top Half
[[ 1.    0.    3.25]
 [ 0.    1.   -0.5 ]]


# Problem 2

In [6]:
data = linear.separate(filename, '2', 4)
print(data)

[matrix([[ 1.,  0.,  0.,  0.],
        [ 1.,  1.,  0.,  0.],
        [ 1.,  2.,  1.,  0.],
        [ 1.,  3.,  3.,  1.]]), matrix([[ 1.,  0.,  0.,  0.],
        [-1.,  1.,  0.,  0.],
        [ 0., -1.,  1.,  0.],
        [ 0.,  0., -1.,  1.]])]


In [7]:
output2 = linear.rref(data[1])

Bottom half
[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0. -1.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
Divide
Top Half


In [8]:
multiplier = linear.multiply(output2)

[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]
[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 1. -2.  1.  0.]
 [ 0.  1. -2.  1.]]
[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 1. -2.  1.  0.]
 [-1.  3. -3.  1.]]
[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 1. -2.  1.  0.]
 [-1.  3. -3.  1.]]


In [9]:
print(multiplier @ data[0])

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [10]:
linear.multiply([data[0]] + output2)

[[ 1.  0.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  2.  1.  0.]
 [ 1.  3.  3.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  2.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


matrix([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]])