In [1]:
import pandas as pd, linear, numpy as np
filename = '3 Multiplication and Inverse Matrices.xlsx'

# Recitation
    Matrix is not invertible if A(c,d,e) = 0
    ca+db+eb=0
    ca+da+eb=0
    ca+da+ea=0
    c+d+e = 0
    c = -d-e
    a(-d-e) + db + eb = 0
    da + ea = db + eb
    a = b
    
Answer

    If a = 0 (row/column = 0)


In [2]:
dataR = linear.separate(filename, 'R2', 3)
print(dataR)

[matrix([[ 2.,  1.,  1.,  1.,  0.,  0.],
        [ 2.,  2.,  1.,  0.,  1.,  0.],
        [ 2.,  2.,  2.,  0.,  0.,  1.]])]


In [3]:
outputR = linear.rref(dataR[0])

Bottom half
[[ 2.  1.  1.  1.  0.  0.]
 [ 2.  2.  1.  0.  1.  0.]
 [ 2.  2.  2.  0.  0.  1.]]
[[ 2.  1.  1.  1.  0.  0.]
 [ 0.  1.  0. -1.  1.  0.]
 [ 0.  1.  1. -1.  0.  1.]]
[[ 2.  1.  1.  1.  0.  0.]
 [ 0.  1.  0. -1.  1.  0.]
 [ 0.  0.  1.  0. -1.  1.]]
Divide
[[ 1.   0.5  0.5  0.5  0.   0. ]
 [ 0.   1.   0.  -1.   1.   0. ]
 [ 0.   0.   1.   0.  -1.   1. ]]
Top Half
[[ 1.   0.5  0.   0.5  0.5 -0.5]
 [ 0.   1.   0.  -1.   1.   0. ]
 [ 0.   0.   1.   0.  -1.   1. ]]
[[ 1.   0.   0.   1.   0.  -0.5]
 [ 0.   1.   0.  -1.   1.   0. ]
 [ 0.   0.   1.   0.  -1.   1. ]]


# Problem 1

In [4]:
data1 = linear.separate(filename, '1', 2)
print(data1)

[matrix([[ 1.,  2.],
        [ 3.,  4.]]), matrix([[ 1.,  0.],
        [ 0.,  0.]]), matrix([[ 0.,  0.],
        [ 5.,  6.]])]


In [5]:
print(data1[0] @ data1[1] + data1[0] @ data1[2])
print(data1[0] @ (data1[1] + data1[2]))

[[ 11.  12.]
 [ 23.  24.]]
[[ 11.  12.]
 [ 23.  24.]]


# Problem 2

In [6]:
data2 = linear.separate(filename, '22', 3)
output2 = linear.rref(data2[0])

Bottom half
[[ 1.  3.  4.  1.  0.  0.]
 [ 0.  1.  5.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  1.]]
Divide
Top Half
[[ 1.  3.  0.  1.  0. -4.]
 [ 0.  1.  0.  0.  1. -5.]
 [ 0.  0.  1.  0.  0.  1.]]
[[  1.   0.   0.   1.  -3.  11.]
 [  0.   1.   0.   0.   1.  -5.]
 [  0.   0.   1.   0.   0.   1.]]
