In [1]:
import linear, numpy as np

# Lecture

In [2]:
a = np.array([ [1,2,2,2], [2,4,6,8], [3,6,8,10], ])
_ = linear.rref(a)

Bottom half
[[  1.   2.   2.   2.]
 [  2.   4.   6.   8.]
 [  3.   6.   8.  10.]]
[[ 1.  2.  2.  2.]
 [ 0.  0.  2.  4.]
 [ 0.  0.  2.  4.]]
[[ 1.  2.  2.  2.]
 [ 0.  0.  2.  4.]
 [ 0.  0.  0.  0.]]
Divide
[[ 1.  2.  2.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]]
Top Half
[[ 1.  2.  0. -2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]]


In [3]:
_ = linear.rref(a.T)

Bottom half
[[  1.   2.   3.]
 [  2.   4.   6.]
 [  2.   6.   8.]
 [  2.   8.  10.]]
[[ 1.  2.  3.]
 [ 0.  0.  0.]
 [ 0.  2.  2.]
 [ 0.  4.  4.]]
[[ 1.  2.  3.]
 [ 0.  2.  2.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Divide
[[ 1.  2.  3.]
 [ 0.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Top Half
[[ 1.  0.  1.]
 [ 0.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


# Recitation

The set $S$ of points $P(x,y,z)$ such that $x - 5y + 2z = 9$ is a plane in $\mathbb{R}^3$

It is parallel to the plane $S_0$ of $P(x,y,z)$ such that $x - 5y + 2z = 0$

All points on S satisfy the equation

$ \begin{bmatrix} x \\ y \\ z \\ \end{bmatrix} = \begin{bmatrix} 9 \\ 0 \\ 0 \\ \end{bmatrix} + c_1 \begin{bmatrix} 5 \\ 1 \\ 0 \\ \end{bmatrix} + c_2 \begin{bmatrix} -2 \\ 0 \\ 1 \\ \end{bmatrix} $

# Problem Set

## 1

a. Find the row reduced form of 

$A = \begin{bmatrix} 1 & 5 & 7 & 9 \\ 0 & 4 & 1 & 7 \\ 2 & -2 & 11 & -3 \end{bmatrix} $

b. What is the rank of this matrix?

Rank is 2

c. Find any special solutions to the equation Ax = 0

$ \begin{bmatrix} -5.75 & -0.25 \\ -0.25 & -1.75 \\ 1 & 0 \\ 0 & 1 \end{bmatrix} $

In [4]:
p1 = np.array([ [1,5,7,9], [0,4,1,7], [2,-2,11,-3], ])
_ = linear.rref(p1)

Bottom half
[[  1.   5.   7.   9.]
 [  0.   4.   1.   7.]
 [  2.  -2.  11.  -3.]]
[[  1.   5.   7.   9.]
 [  0.   4.   1.   7.]
 [  0. -12.  -3. -21.]]
[[ 1.  5.  7.  9.]
 [ 0.  4.  1.  7.]
 [ 0.  0.  0.  0.]]
Divide
[[ 1.    5.    7.    9.  ]
 [ 0.    1.    0.25  1.75]
 [ 0.    0.    0.    0.  ]]
Top Half
[[ 1.    0.    5.75  0.25]
 [ 0.    1.    0.25  1.75]
 [ 0.    0.    0.    0.  ]]


## 2

Find $A_1$ and $A_2$ so that rank($A_1B$) = 1 and rank($A_2B$) = 0 for 

$ B = \begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix} $

In [5]:
b = np.array([
    [1,1],
    [1,1]
])
a1 = np.array([
    [1,1],
    [0,0]
])
a2 = np.array([
    [0,0],
    [0,0]
])
_ = linear.rref(a1 @ b)
_ = linear.rref(a2 @ b)

Bottom half
[[ 2.  2.]
 [ 0.  0.]]
Divide
[[ 1.  1.]
 [ 0.  0.]]
Top Half
Bottom half
[[ 0.  0.]
 [ 0.  0.]]
Divide
Top Half
