In [1]:
import linear, numpy as np

# Lecture

In [2]:
l = np.array([
    [1,3],
    [2,1],
    [6,1],
    [5,1],
])

_ = linear.rref(l)

Bottom half
[[ 1.  3.]
 [ 2.  1.]
 [ 6.  1.]
 [ 5.  1.]]
[[  1.   3.]
 [  0.  -5.]
 [  0. -17.]
 [  0. -14.]]
[[ 1.  3.]
 [ 0. -5.]
 [ 0.  0.]
 [ 0.  0.]]
Divide
[[ 1.  3.]
 [-0.  1.]
 [ 0.  0.]
 [ 0.  0.]]
Top Half
[[ 1.  0.]
 [-0.  1.]
 [ 0.  0.]
 [ 0.  0.]]


In [3]:
_ = linear.rref(l.T)

Bottom half
[[ 1.  2.  6.  5.]
 [ 3.  1.  1.  1.]]
[[  1.   2.   6.   5.]
 [  0.  -5. -17. -14.]]
Divide
[[ 1.   2.   6.   5. ]
 [-0.   1.   3.4  2.8]]
Top Half
[[ 1.   0.  -0.8 -0.6]
 [-0.   1.   3.4  2.8]]


# Recitation
Find all solutions to matrix  
$ \begin{bmatrix} 1 & -2 & -2\\ 2 & -5 & -4\\ 4 & -9 & -8 \end{bmatrix} \\
\begin{bmatrix} b1 \\ b2 \\ b3 \end{bmatrix}
=> \begin{bmatrix} b1 \\ b2 - 2b1 \\ b3 - 4b1 \end{bmatrix}
=> \begin{bmatrix} b1 \\ b2 - 2b1 \\ b3 - b2 - 2b1 \end{bmatrix}
=> \begin{bmatrix} b1 \\ 2b1 - b2 \\ b3 - b2 - 2b1 \end{bmatrix}
=> \begin{bmatrix} 5b1 - b2 \\ 2b1 - b2 \\ b3 - b2 - 2b1 \end{bmatrix}
$  
Solution:  
$ 
\begin{bmatrix} 5b1 - b1 \\ 2b1 - b2 \\ 0 \end{bmatrix} + c \begin{bmatrix} 2 \\ 0 \\ 1 \end{bmatrix}
$  

In [4]:
r = np.array([
    [1,-2,-2],
    [2,-5,-4],
    [4,-9,-8],
])

_ = linear.rref(r)

Bottom half
[[ 1. -2. -2.]
 [ 2. -5. -4.]
 [ 4. -9. -8.]]
[[ 1. -2. -2.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]]
[[ 1. -2. -2.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
Divide
[[ 1. -2. -2.]
 [-0.  1. -0.]
 [ 0.  0.  0.]]
Top Half
[[ 1.  0. -2.]
 [-0.  1. -0.]
 [ 0.  0.  0.]]


# Problem Set

## 1
Explain why these are all false  
a) The complete solution is any linear combination of xp and xn.  
The complete solution is xp plus any linear combination of xn.  
b) The system Ax = b has at most one particular solution.  
If free variables exist, Ax = b has infinite solutions  
c) If A is invertible there is no solution xn in the nullspace.  
If A is invertible, nullspace is origin  

## 2
Use Gauss-Jordan elimination to reduce the matrices [U 0] and [U c]  
to [R 0] and [R d]. Solve Rx = 0 and Rx = d.  
Check your work by plugging your values into the equations Ux = 0  
and Ux = c.  

In [5]:
p1 = np.array([
    [1,2,3,5],
    [0,0,4,8],
])
_ = linear.rref(p1)
u = p1[:,0:3]
print(u)
x0 = np.array([-2,1,0]).T
xd = np.array([-1,0,2]).T
print(u @ x0)
print(u @ xd)

Bottom half
[[ 1.  2.  3.  5.]
 [ 0.  0.  4.  8.]]
Divide
[[ 1.  2.  3.  5.]
 [ 0.  0.  1.  2.]]
Top Half
[[ 1.  2.  0. -1.]
 [ 0.  0.  1.  2.]]
[[1 2 3]
 [0 0 4]]
[0 0]
[5 8]


$
Rx = 0 \\
c\begin{bmatrix} -2 \\ 1 \\ 0 \end{bmatrix} \\
Rx = d \\
\begin{bmatrix} -1 \\ 0 \\ 2 \end{bmatrix}
$

## 3
Suppose Ax = b and Cx = b have the same
(complete) solutions for every b. Is it true that A = C?  
Yes