In [1]:
import linear, numpy as np

# Recitation

3 dimensions  
basis is  
$ \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix} $

In [2]:
r = np.array([
    [1,1,-2,0,-1],
    [1,2,0,-4,1],
    [0,1,3,-3,2],
    [2,3,0,-2,0],
])
_ = linear.rref(r)

Bottom half
[[ 1.  1. -2.  0. -1.]
 [ 1.  2.  0. -4.  1.]
 [ 0.  1.  3. -3.  2.]
 [ 2.  3.  0. -2.  0.]]
[[ 1.  1. -2.  0. -1.]
 [ 0.  1.  2. -4.  2.]
 [ 0.  1.  3. -3.  2.]
 [ 0.  1.  4. -2.  2.]]
[[ 1.  1. -2.  0. -1.]
 [ 0.  1.  2. -4.  2.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0.  2.  2.  0.]]
[[ 1.  1. -2.  0. -1.]
 [ 0.  1.  2. -4.  2.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]
Divide
Top Half
[[ 1.  1.  0.  2. -1.]
 [ 0.  1.  0. -6.  2.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  0.  0.  8. -3.]
 [ 0.  1.  0. -6.  2.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]


# Problem Set

## 1
Find the largest
possible number of independent vectors  
4

In [3]:
p1 = np.array([
    [1,1,0,0,0,0],
    [-1,0,0,1,1,0],
    [0,-1,0,-1,0,1],
    [0,0,-1,0,-1,-1],
])
_ = linear.rref(p1)

Bottom half
[[ 1.  1.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  1.  0.]
 [ 0. -1.  0. -1.  0.  1.]
 [ 0.  0. -1.  0. -1. -1.]]
[[ 1.  1.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  1.  0.]
 [ 0. -1.  0. -1.  0.  1.]
 [ 0.  0. -1.  0. -1. -1.]]
[[ 1.  1.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  1.  1.]
 [ 0.  0. -1.  0. -1. -1.]]
[[ 1.  1.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  1.  0.]
 [ 0.  0. -1.  0. -1. -1.]
 [ 0.  0.  0.  0.  1.  1.]]
Divide
[[ 1.  1.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  1.  0.]
 [-0. -0.  1. -0.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.]]
Top Half
[[ 1.  1.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0. -1.]
 [-0. -0.  1. -0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.]]
[[ 1.  0.  0. -1.  0.  1.]
 [ 0.  1.  0.  1.  0. -1.]
 [-0. -0.  1. -0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.]]


## 2
Find a basis for the plane $x − 2y + 3z = 0$ in $\mathbb{R}^3$.  
$\begin{bmatrix} 2 & -3 \\ 1 & 0 \\ 0 & 1 \end{bmatrix}$  
Then find a basis for the intersection of that plane with the $xy$ plane.  
$\begin{bmatrix} 2 \\ 1 \\ 0 \end{bmatrix}$  
Then find a basis for all vectors perpendicular to the plane.  

In [4]:
p2 = np.array([
    [2,-3],
    [1,0],
    [0,1],
])
linear.crossProduct(p2.T)

matrix([[ 1., -2.,  3.]])