In [3]:
import linear, numpy as np

# 1
This question is about an m by n matrix A for which  
Ax = [1,1,1] has no solutions and Ax = [0,1,0] has exactly one solution.  
(a) Give all possible information about m and n and the rank r of A.  
m = 3 because Ax is $\mathbb{R}^3$.  
Column rank is full because Ax = b has one solution.  
Row rank is not full Ax = b does not exist for all solutions.  
Therefore r = n = 1 or 2  
(b) Find all solutions to Ax = 0 and explain your answer.  
Solutions to Ax = 0 = origin, because Ax = b only has one solution.  
(c) Write down an example of a matrix A that fits the description in
part (a).  
A = [0,1,0]  

Correct

# 2
The 3 by 3 matrix A reduces to the identity matrix I by the following three
row operations (in order):  
E21 : Subtract 4 (row 1) from row 2.  
E31 : Subtract 3 (row 1) from row 3.  
E23 : Subtract row 3 from row 2.  
(a) Write the inverse matrix A−1 in terms of the E’s. Then compute A−1.  
E23 @ E31 @ E21 @ A = I  
A = A.I @ I = A.I = E21.I @ E31.I @ E23.I @ I  
A.I = $ \begin{bmatrix} 1 & 0 & 0 \\ 4 & 1 & 0 \\ 3 & 1 & 1 \end{bmatrix} $  

Wrong. A.I @ A = I  
A.I = E23 @ E31 @ E21  

(b) What is the original matrix A ?  
A = A.I @ I = A.I  

Wrong. 1 should be in 1,2, not 2,1

(c) What is the lower triangular factor L in A = LU ?  
U = identity, because elimination produces identity. 
A = LU = LI = A.I @ I  
Therefore L = A.I = A  

Correct. Carried forward error from b

In [9]:
AI = np.identity(3)
AI[1,0] = 4
AI[2,0] = 3
AI[1,2] = 1
A = AI
E = [np.identity(3) for i in range(3)]
E[0][1,0] = -4
E[1][2,0] = -3
E[2][1,2] = -1
_ = linear.multiply(E)

[[ 1.  0.  0.]
 [-4.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [-4.  1.  0.]
 [-3.  0.  1.]]
[[ 1.  0.  0.]
 [-1.  1. -1.]
 [-3.  0.  1.]]


# 3
This 3 by 4 matrix depends on c:  
$ \begin{bmatrix} 1 & 1 & 2 & 4 \\ 3 & 3 & 2 & 8 \\ 0 & 0 & 2 & 2 \end{bmatrix} $  
(a) For each c find a basis for the column space of A.  
For c = 3, basis = $ \begin{bmatrix} 1 & 2 \\ 3 & 2 \\ 0 & 2 \end{bmatrix} $  
For c != 3, basis = $ \begin{bmatrix} 1 & 1 & 2 \\ 3 & c & 2 \\ 0 & 0 & 2 \end{bmatrix} $  
(b) For each c find a basis for the nullspace of A.  
For c = 3, nullspace = $ \begin{bmatrix} -1 & -2 \\ 1 & 0 \\ 0 & -1 \\ 0 & 1 \end{bmatrix} $  
For c != 3 nullspace = $ \begin{bmatrix} -2 \\ 0 \\ -1 \\ 1 \end{bmatrix} $  
(c) For each c find the complete solution x to Ax = [1,c,0]  
For c = 3, solution = [1,0,0,0] + nullspace  
For c != 3, Xp = [0,1,0,0] + nullspace

Correct

In [42]:
for c in 3, 4:
    A3 = np.array([
        [1,1,2,4],
        [3,c,2,8],
        [0,0,2,2],
    ])
#     print(linear.toTex(A3[:,[0,1,2]]))
    outcome = linear.rref(np.concatenate((A3, np.array([[1,c,0]]).T), axis=1))[-1][:,:-1]
#     print(A3 @ np.array([1,0,0,0]))
#     print(A3 @ np.array([0,1,0,0]))

[[ 1.  1.  2.  4.  1.]
 [ 3.  3.  2.  8.  3.]
 [ 0.  0.  2.  2.  0.]]
[[ 1.  1.  2.  4.  1.]
 [ 0.  0. -4. -4.  0.]
 [ 0.  0.  2.  2.  0.]]
[[ 1.  1.  2.  4.  1.]
 [ 0.  0. -4. -4.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 1.  1.  2.  4.  1.]
 [-0. -0.  1.  1. -0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  0.  2.  1.]
 [-0. -0.  1.  1. -0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  2.  4.  1.]
 [ 3.  4.  2.  8.  4.]
 [ 0.  0.  2.  2.  0.]]
[[ 1.  1.  2.  4.  1.]
 [ 0.  1. -4. -4.  1.]
 [ 0.  0.  2.  2.  0.]]

[[ 1.  1.  2.  4.  1.]
 [ 0.  1. -4. -4.  1.]
 [ 0.  0.  1.  1.  0.]]
[[ 1.  1.  0.  2.  1.]
 [ 0.  1.  0.  0.  1.]
 [ 0.  0.  1.  1.  0.]]
[[ 1.  0.  0.  2.  0.]
 [ 0.  1.  0.  0.  1.]
 [ 0.  0.  1.  1.  0.]]


# 4
(a)	 If A is a 3 by 5 matrix, what information do you have about the
nullspace of A ?  
Nullspace is 5 by (2 to 4)  
(b) Suppose row operations on A lead to this matrix R = rref(A):  
$ \begin{bmatrix} 1 & 4 & 0 & 0 & 0 \\ 0 & 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 0 & 1 \end{bmatrix} $  
Write all known information about the columns of A.  
Columns 2 = 4 * column 1.  
Column 3 = 0s.  
Column 4 and 5 are independent of 1/2/3.  
(c) In the vector space M of all 3 by 3 matrices (you could call this a
matrix space), what subspace S is spanned by all possible row reduced
echelon forms R ?  
Space of upper right matrices.  

Correct