In [1]:
import linear, numpy as np

# Recitation
S is spanned by [1, 2, 2, 3] and [1, 3, 3, 2]  

1. Find a basis for ST  
$ \begin{bmatrix} 0 & -5 \\ -1 & 1 \\ 1 & 0 \\ 0 & 1 \end{bmatrix} $  
2. Can every v in $\mathbb{R}^4$ be written uniquely in terms of S and ST

In [2]:
SR = np.array([
    [1, 2, 2, 3], 
    [1, 3, 3, 2], 
])
_ = linear.rref(SR)

Bottom half
[[ 1.  2.  2.  3.]
 [ 1.  3.  3.  2.]]
[[ 1.  2.  2.  3.]
 [ 0.  1.  1. -1.]]
Divide
Top Half
[[ 1.  0.  0.  5.]
 [ 0.  1.  1. -1.]]


In [3]:
nullR = linear.toMatrix('$ \begin{bmatrix} 0 & -5 \\ -1 & 1 \\ 1 & 0 \\ 0 & 1 \end{bmatrix} $  ')
array4 = np.concatenate((SR, nullR.T))
_ = linear.rref(array4)

Bottom half
[[ 1.  2.  2.  3.]
 [ 1.  3.  3.  2.]
 [ 0. -1.  1.  0.]
 [-5.  1.  0.  1.]]
[[  1.   2.   2.   3.]
 [  0.   1.   1.  -1.]
 [  0.  -1.   1.   0.]
 [  0.  11.  10.  16.]]
[[  1.   2.   2.   3.]
 [  0.   1.   1.  -1.]
 [  0.   0.   2.  -1.]
 [  0.   0.  -1.  27.]]
[[  1.    2.    2.    3. ]
 [  0.    1.    1.   -1. ]
 [  0.    0.    2.   -1. ]
 [  0.    0.    0.   26.5]]
Divide
[[ 1.   2.   2.   3. ]
 [ 0.   1.   1.  -1. ]
 [ 0.   0.   1.  -0.5]
 [ 0.   0.   0.   1. ]]
Top Half
[[ 1.  2.  2.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  2.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [4]:
# output = linear.rref(np.concatenate((array4, np.identity(4)), axis=1))
# print(output[-1][:,4:])

# Problem Set
## 1
For every
system of m equations with no solution, there are numbers y1, ..., ym that
multiply the equations so they add up to 0 = 1. This is called Fredholm’s
Alternative:  

Exactly one of these problems has a solution:  
Ax = b OR ATy = 0 with yTb = 1.  

If b is not in the column space of A it is not orthogonal to the nullspace of
AT. Multiply the equations x1 − x2 = 1, x2 − x3 = 1 and x1 − x3 = 1 by
numbers y1, y2 and y3 chosen so that the equations add up to 0 = 1.  

y.T b = x  
y.T @ b / x = 1  
(y/x).T @ b = 1  

y/x = y/-1 = $ \begin{bmatrix} 1 \\ 1 \\ -1 \end{bmatrix} $  

In [5]:
p1 = np.array([
    [1, -1, 0],
    [0, 1, -1],
    [1, 0, -1],
])
_ = linear.rref(p1.T)
# Nullspace of A.T
y = np.array([[-1, -1, 1]]).T
# Show that it equals 0
print(p1.T @ y)
b = np.array([1,1,1])
print(y.T @ b)
print(linear.toTex(y.T / -1))

Bottom half
[[ 1.  0.  1.]
 [-1.  1.  0.]
 [ 0. -1. -1.]]
[[ 1.  0.  1.]
 [ 0.  1.  1.]
 [ 0. -1. -1.]]
[[ 1.  0.  1.]
 [ 0.  1.  1.]
 [ 0.  0.  0.]]
Divide
Top Half
[[0]
 [0]
 [0]]
[-1]
$ \begin{bmatrix} 1 & 1 & -1 \end{bmatrix} $


## 2
Suppose I give you four nonzero vectors r, n, c
and l in R2.  
a) What are the conditions for those to be bases for the four fundamental
subspaces C(AT), N(A), C(A), and N(AT) of a 2 by 2 matrix?  
rank must be 1, so that column and row space dimensions = rank = 1, and null space = n - 1 = 1, and left null space = m - 1 = 1  
Also r.n = 0, and c.l = 0  
b) What is one possible matrix A?  

In [7]:
p2 = np.array([
    [1,-1],
    [0,0],
])
_ = linear.rrefIdentity(p2)
r = np.array([[1, -1]]).T
c = np.array([[1, 0]]).T
n = np.array([[1, 1]]).T
l = np.array([[0,1]]).T
print(c @ r.T)
print(p2 @ n)
print(l.T @ p2)

Bottom half
[[ 1. -1.  1.  0.]
 [ 0.  0.  0.  1.]]
Divide
Top Half
[[ 1 -1]
 [ 0  0]]
[[0]
 [0]]
[[0 0]]
