In [1]:
import linear, numpy as np, datetime

# Lecture
(-1-l)(-2-l) - 2 = 0  
2 + 3l + l2 - 2 = l  
(l + 3)l = 0

In [2]:
al = np.matrix([
    [-1,2],
    [1,-2],
])
ul = np.matrix([1,0]).T
el = [0, -3]
for k in range(0, 10, 2):
    print(linear.aku0(al, el, linear.diagonalExp, ul, k))

[[  1.00000000e+00]
 [  5.55111512e-17]]
[[ 0.66749292]
 [ 0.33250708]]
[[ 0.66666871]
 [ 0.33333129]]
[[ 0.66666667]
 [ 0.33333333]]
[[ 0.66666667]
 [ 0.33333333]]


# Recitation
Solve the differential equation  
y''' + 2y'' - y' - 2y = 0  
What is the matrix A?  
Find the first column of exp(At)  
(-2-l)(-l)(-l) + l + 2  
= - l3 -2l2 + l + 2
(1-l)(1+l)(2+l)  
As t goes to infinity, e^(lt) goes to infinity

In [5]:
ar = np.matrix([
    [-2, 1, 2],
    [1, 0, 0],
    [0, 1, 0],
])
er = (1, -1, -2)
sr = linear.eigenVectors(ar, er)
print(sr)
print(sr.I)

1 [[ 1.  1.  1.]] [[ 1.  1.  1.]] [[ 1.  1.  1.]]
-1 [[ 1. -1.  1.]] [[-1.  1. -1.]] [[-1.  1. -1.]]
-2 [[ 4. -2.  1.]] [[-8.  4. -2.]] [[-8.  4. -2.]]
[[ 1.  1.  4.]
 [ 1. -1. -2.]
 [ 1.  1.  1.]]
[[ 0.16666667  0.5         0.33333333]
 [-0.5        -0.5         1.        ]
 [ 0.33333333 -0.         -0.33333333]]


# Problem Set
## 1
Don't understand

## 2
(1-l)(3-l) = 0

In [9]:
ap2 = np.matrix([
    [1,1],
    [0,3],
])
ep2 = [1, 3]
sp2 = linear.eigenVectors(ap2, ep2)
print(sp2)
print(sp2.I)

1 [[ 1. -0.]] [[ 1.  0.]] [[ 1.  0.]]
3 [[ 0.5  1. ]] [[ 1.5  3. ]] [[ 1.5  3. ]]
[[ 1.   0.5]
 [-0.   1. ]]
[[ 1.  -0.5]
 [ 0.   1. ]]
