In [1]:
import linear, numpy as np

# Lecture

In [2]:
al = np.matrix([
    [0.1, 0.01, 0.3],
    [0.2, 0.99, 0.3],
    [0.7, 0, 0.4],
])
el = [1]
_ = linear.eigenVectors(al, el)
_ = linear.eigenVectors(al.T, el)

1 [[  0.85714286  47.14285701   1.        ]] [[  0.85714286  47.14285701   1.        ]] [[  0.85714286  47.14285701   1.        ]]
1 [[ 1.  1.  1.]] [[ 1.  1.  1.]] [[ 1.  1.  1.]]


In [3]:
al2 = np.matrix([
    [0.9, 0.2],
    [0.1, 0.8],
])
ul2 = np.matrix([0, 1000]).T
el2 = linear.eigen2x2(al2)
gap = 10
sl2 = linear.eigenVectors(al2, el2.round(8), 'Silent')
linear.multiplyR([sl2, linear.diagonal(el2.round(8), 10000), sl2.I])
for i in range(0, 5 * gap, gap):
#     print(sl2 @ linear.diagonal(el2.round(8), i) @ sl2.I)
    print(linear.aku0(al2, el2.round(8), linear.diagonal, ul2, i))

[[ 2. -1.]
 [ 1.  1.]]
[[ 2.  0.]
 [ 1.  0.]]
[[ 0.66666667  0.66666667]
 [ 0.33333333  0.33333333]]
[[    0.]
 [ 1000.]]
[[ 647.8349834]
 [ 352.1650166]]
[[ 666.13471822]
 [ 333.86528178]]
[[ 666.65164044]
 [ 333.34835956]]
[[ 666.66624221]
 [ 333.33375779]]


# Recitation
Find $S\Lambda ^kS^{-1}$ for k = 1, n, infinity  
$ = 
\begin{bmatrix} 0.5 & -1.0 \\ 1.0 & 1.0 \end{bmatrix}
\begin{bmatrix} 1 & 0 \\ 0 & 0.4^t \end{bmatrix}
\begin{bmatrix} 2/3 \\ -2/3 \end{bmatrix} \\
= \begin{bmatrix} 0.5 & -0.4^t \\ 1 & 0.4^t \end{bmatrix} 
\begin{bmatrix} 2/3 \\ -2/3 \end{bmatrix} \\
= \frac{2}{3}\begin{bmatrix} 0.5 + 0.4^t \\ 1 - 0.4^t \end{bmatrix} \\
k = 1 => \begin{bmatrix} 0.6 \\ 0.4 \end{bmatrix} \\
k = \infty => \begin{bmatrix} 1/3 \\ 2/3 \end{bmatrix}
$

In [18]:
ar = np.matrix([
    [0.6,0.2],
    [0.4,0.8],
])
ur = np.matrix([1,0]).T
er = linear.eigen2x2(ar).round(3)
sr = linear.eigenVectors(ar, er, 'Silent')
print(linear.toTex(sr))
print(linear.toTex(linear.diagonal(er)))
print(linear.toTex(sr.I @ ur))
for i in 1, 10000:
    print(linear.aku0(ar, er, linear.diagonal, ur, i))

$ \begin{bmatrix} 0.5 & -1.0 \\ 1.0 & 1.0 \end{bmatrix} $
$ \begin{bmatrix} 1.0 & 0.0 \\ 0.0 & 0.4 \end{bmatrix} $
$ \begin{bmatrix} 0.666666666667 \\ -0.666666666667 \end{bmatrix} $
[[ 0.6]
 [ 0.4]]
[[ 0.33333333]
 [ 0.66666667]]


# Problem Set
## 1. 
### a. 
a) Find a symmetric matrix that has a negative eigenvalue.  

$\begin{bmatrix} 1 & b \\ b & 1 \end{bmatrix} \\
(1-l)(1-l) - b^2 = 0 \\
1 - 2l + l^2 - b^2 = 0 \\
l^2 - 2l - b^2 + 1 \\
(4 - 4(-b^2 + 1)) > 4 \\
b^2 > 1
$
### b. 
How do you know it must have a negative pivot?  

$R = \begin{bmatrix} 1 & 0 \\ 0 & 1-b^2 \end{bmatrix} $  
Since $b^2 > 1, 1 - b^2 < 0$
### c. 
How do you know it can’t have two negative eigenvalues?  
Because $-b = 2 > 0$, therefore $-b + \sqrt{b^2 - 4ac} > 0$

## 2. 
Which of these classes of matrices do A and B
belong to: invertible, orthogonal, projection, permutation, diagonalizable,
Markov?  
$ A = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}\ 
B = \frac{1}{3} \begin{bmatrix} 1 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 1 \end{bmatrix} $  
A is invertible, orthogonal, permutation, diagonalizable, Markov  
B is Markov, diagonalizable, projection  
LU is possible for B  
QR is possible for A  
SLS.I/QLQ.T is possible for A and B  
