In [1]:
import linear, numpy as np

# Recitation
Find all the non-zero terms in the big formula det A = Sigma
and compute detA  
You only need to compute combinations of 1,2,5,6 and 9,10,11,12  
Find cofactors C11, C12, C13, C14  
Find column 1 of A-1

In [4]:
ar = np.matrix([
    [1,2,3,4],
    [5,6,7,8],
    [0,0,9,10],
    [0,0,11,12],
])
d = linear.det(ar)
c = linear.cofactor(ar)
print(d)
print(c)
print(c.T / d)
print(ar.I)

[[  1.           2.           3.           4.        ]
 [  0.          -4.          -8.         -12.        ]
 [  0.           0.           9.          10.        ]
 [  0.           0.           0.          -0.22222222]]
7.9999999992
[[-12.  10.   0.  -0.]
 [  4.  -2.  -0.   0.]
 [ 40. -36. -48.  44.]
 [-32.  28.  40. -36.]]
[[-1.5   0.5   5.   -4.  ]
 [ 1.25 -0.25 -4.5   3.5 ]
 [ 0.   -0.   -6.    5.  ]
 [-0.    0.    5.5  -4.5 ]]
[[-1.5   0.5   5.   -4.  ]
 [ 1.25 -0.25 -4.5   3.5 ]
 [ 0.    0.   -6.    5.  ]
 [ 0.    0.    5.5  -4.5 ]]
