In [1]:
import linear, numpy as np

# Recitation
Find the orthogonal projection matrix onto the plane  
x + y - z = 0  

In [2]:
ar = np.matrix([
    [-1, 1],
    [1, 0],
    [0, 1],
])
par = linear.projection(ar)
nr = np.matrix([[1,1,-1]]).T
pnr = np.identity(3) - linear.projection(nr)
print(par*3)
print(pnr*3)

Arrays
[[-1  1  0]
 [ 1  0  1]]
[[ 0.66666667  0.33333333]
 [ 0.33333333  0.66666667]]
[[-1  1]
 [ 1  0]
 [ 0  1]]
Multiply
[[-1  1  0]
 [ 1  0  1]]
[[-0.33333333  0.66666667  0.33333333]
 [ 0.33333333  0.33333333  0.66666667]]
[[ 0.66666667 -0.33333333  0.33333333]
 [-0.33333333  0.66666667  0.33333333]
 [ 0.33333333  0.33333333  0.66666667]]
Arrays
[[ 1  1 -1]]
[[ 0.33333333]]
[[ 1]
 [ 1]
 [-1]]
Multiply
[[ 1  1 -1]]
[[ 0.33333333  0.33333333 -0.33333333]]
[[ 0.33333333  0.33333333 -0.33333333]
 [ 0.33333333  0.33333333 -0.33333333]
 [-0.33333333 -0.33333333  0.33333333]]
[[ 2. -1.  1.]
 [-1.  2.  1.]
 [ 1.  1.  2.]]
[[ 2. -1.  1.]
 [-1.  2.  1.]
 [ 1.  1.  2.]]


# Problem Set
## 1
Suppose A
is the four by four identity matrix with its last column removed; A is four
by three. Project b = (1, 2, 3, 4) onto the column space of A. What shape is
the projection matrix P and what is P?

In [3]:
ap1 = np.matrix(np.identity(4)[:,:3])
pp1 = linear.projection(ap1)
bp1 = np.matrix([[1,2,3,4]]).T
print(pp1 @ bp1)

Arrays
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
Multiply
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.]
 [ 2.]
 [ 3.]
 [ 0.]]


## 2
If P2 = P, show that (I − P)2 = I − P.  
(I - P)2 = I2 - IP - PI + P2 = I - 2P + P = I - P
For the
matrices A and P from the previous question, P projects onto the column
space of A and I − P projects onto the normal of A. 

Clarify - left nullspace, not just normal