In [1]:
import linear, numpy as np

# Lecture

In [2]:
al = np.matrix([
    [1,1],
    [1,2],
    [1,3],
])
bl = np.matrix([[1,2,2]]).T
fitl = linear.projection(al) @ bl
el = bl - fitl
print(fitl.T, el.T)
print(el.T @ al, el.T @ fitl)

Arrays
[[1 1 1]
 [1 2 3]]
[[ 2.33333333 -1.        ]
 [-1.          0.5       ]]
[[1 1]
 [1 2]
 [1 3]]
Multiply
[[1 1 1]
 [1 2 3]]
[[ 1.33333333  0.33333333 -0.66666667]
 [-0.5         0.          0.5       ]]
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]
[[ 1.16666667  1.66666667  2.16666667]] [[-0.16666667  0.33333333 -0.16666667]]
[[  4.44089210e-15   8.88178420e-15]] [[  7.43849426e-15]]


# Recitation
Find the quadratic equation through the origin that is a best fit for the points
[1,1], [2,5], [-1,-2]

In [3]:
ar = np.matrix([
    [1,2,-1],
    [1,4,1],
]).T
br = np.matrix([[1,5,-2]]).T
fitr = linear.projection(ar) @ br
print(ar.I @ fitr)
print(fitr)
totalr = ar.T @ np.concatenate((ar, br), axis=1)
_ = linear.rref(totalr)

Arrays
[[ 1  2 -1]
 [ 1  4  1]]
[[ 0.40909091 -0.18181818]
 [-0.18181818  0.13636364]]
[[ 1  1]
 [ 2  4]
 [-1  1]]
Multiply
[[ 1  2 -1]
 [ 1  4  1]]
[[ 0.22727273  0.09090909 -0.59090909]
 [-0.04545455  0.18181818  0.31818182]]
[[ 0.18181818  0.27272727 -0.27272727]
 [ 0.27272727  0.90909091  0.09090909]
 [-0.27272727  0.09090909  0.90909091]]
[[ 1.86363636]
 [ 0.22727273]]
[[ 2.09090909]
 [ 4.63636364]
 [-1.63636364]]
Bottom half
[[  6.   8.  13.]
 [  8.  18.  19.]]
[[  6.           8.          13.        ]
 [  0.           7.33333333   1.66666667]]
Divide
[[ 1.          1.33333333  2.16666667]
 [ 0.          1.          0.22727273]]
Top Half
[[ 1.          0.          1.86363636]
 [ 0.          1.          0.22727273]]


# Problem Set
## 1
Write down
three equations for the line b = C + Dt to go through b = 7 at t = −1,
b = 7 at t = 1, and b = 21 at t = 2. Find the least squares solution
xˆ = (C, D) and draw the closest line. 

In [4]:
ap1 = np.matrix([
    [1,-1],
    [1,1],
    [1,2],
])
bp1 = np.matrix([[7,7,21]]).T
pp1 = linear.projection(ap1)
fitp1 = pp1 @ bp1
print(ap1.I @ fitp1)
print(fitp1)

Arrays
[[ 1  1  1]
 [-1  1  2]]
[[ 0.42857143 -0.14285714]
 [-0.14285714  0.21428571]]
[[ 1 -1]
 [ 1  1]
 [ 1  2]]
Multiply
[[ 1  1  1]
 [-1  1  2]]
[[ 0.57142857  0.28571429  0.14285714]
 [-0.35714286  0.07142857  0.28571429]]
[[ 0.92857143  0.21428571 -0.14285714]
 [ 0.21428571  0.35714286  0.42857143]
 [-0.14285714  0.42857143  0.71428571]]
[[ 9.]
 [ 4.]]
[[  5.]
 [ 13.]
 [ 17.]]


## 2
Find the projection p = Ax in the previous problem.
This gives the three heights of the closest line. Show that the error
vector is e = (2, −6, 4). Why is Pe = 0?  
Because P is projection on column space, e is projection on left nullspace, and the two spaces are perpendicular. 

In [5]:
ep2 = bp1 - fitp1
print(ep2)
print(ep2.T @ fitp1)

[[ 2.]
 [-6.]
 [ 4.]]
[[  7.10542736e-14]]


## 3
Suppose the measurements at t = −1, 1, 2 are
the errors 2, -6, 4 in the previous problem. Compute x and the closest
line to these new measurements. Explain the answer: b = (2, −6, 4) is
perpendicular to **column space** so the projection is p = 0. 

In [6]:
fitp3 = pp1 @ ep2
print(fitp3)

[[  1.55431223e-15]
 [  2.66453526e-15]
 [  3.10862447e-15]]


## 4
Suppose the measurements at t = −1, 1, 2 are
b = (5, 13, 17). Compute x and the closest line and e. The error is e = 0
because this b is **in the column space**.

## 5
Which of the four subspaces contains the error
vector e?  
Left null space  
Which contains p?  
Column space  
Which contains xˆ?  
Row space
What is the nullspace of
A?  
origin  
## 6
Find the best line C + Dt to fit b = 4, 2, −1, 0, 0 at
times t = −2, −1, 0, 1, 2. 

In [7]:
ap6 = np.matrix([
    [1,-2],
    [1,-1],
    [1,0],
    [1,1],
    [1,2],
])
bp6 = np.matrix([[4,2,-1,0,0]]).T
fitp6 = linear.projection(ap6) @ bp6
print(ap6.I @ fitp6)
print(fitp6)

Arrays
[[ 1  1  1  1  1]
 [-2 -1  0  1  2]]
[[ 0.2  0. ]
 [ 0.   0.1]]
[[ 1 -2]
 [ 1 -1]
 [ 1  0]
 [ 1  1]
 [ 1  2]]
Multiply
[[ 1  1  1  1  1]
 [-2 -1  0  1  2]]
[[ 0.2  0.2  0.2  0.2  0.2]
 [-0.2 -0.1  0.   0.1  0.2]]
[[ 0.6  0.4  0.2  0.  -0.2]
 [ 0.4  0.3  0.2  0.1  0. ]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.   0.1  0.2  0.3  0.4]
 [-0.2  0.   0.2  0.4  0.6]]
[[ 1.]
 [-1.]]
[[ 3.]
 [ 2.]
 [ 1.]
 [ 0.]
 [-1.]]
