In [1]:
import linear, numpy as np

# Lecture

In [2]:
a = np.matrix([
    [1,1],
    [1,0],
    [1,2],
])
_ = linear.gram(a)

[[ 1.  0.]
 [ 1. -1.]
 [ 1.  1.]]
[[ 0.57735027  0.        ]
 [ 0.57735027 -0.70710678]
 [ 0.57735027  0.70710678]]


# Recitation
Make A orthonormal and write R

In [3]:
ar = np.matrix([
    [1,2,4],
    [0,0,5],
    [0,3,6],
])
qr = linear.gram(ar)
print(qr.T)
rr = qr.T @ ar
print(rr)

[[ 1.  0.  0.]
 [ 0.  0.  5.]
 [ 0.  3.  0.]]
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
[[ 1.  2.  4.]
 [ 0.  3.  6.]
 [ 0.  0.  5.]]


# Problem Set
## 1
Orthonormal vectors are automatically linearly independent.  
Matrix Proof: Show that Qx = 0 implies x = 0. Since Q may be rectangular,
you can use Q.T but not Q.I.  

Stuck  
Qx = 0  
Q.T Qx = Q.T 0 = 0  
Q.T Qx also = Ix  
Ix = 0, therefore x = 0

## 2
Given the vectors a, b and c listed below, use the
Gram-Schmidt process to find orthogonal vectors A, B, and C that span
the same space.  

a = (1, −1, 0, 0), b = (0, 1, −1, 0), c = (0, 0, 1, −1).

Show that {A, B, C} and {a, b, c} are bases for the space of vectors perpendicular
to d = (1, 1, 1, 1). 

In [4]:
ap2 = np.matrix([
    [1,-1,0,0],
    [0,1,-1,0],
    [0,0,1,-1],
]).T.astype(float)
qp2 = linear.gram(ap2)
d = np.matrix([1,1,1,1])
print(d @ ap2)
print(d @ qp2)

[[ 1.          0.5         0.33333333]
 [-1.          0.5         0.33333333]
 [ 0.         -1.          0.33333333]
 [ 0.          0.         -1.        ]]
[[ 0.70710678  0.40824829  0.28867513]
 [-0.70710678  0.40824829  0.28867513]
 [ 0.         -0.81649658  0.28867513]
 [ 0.          0.         -0.8660254 ]]
[[ 0.  0.  0.]]
[[ 0.  0.  0.]]
