In [2]:
import linear, numpy as np

# Recitation
Find the determinant of
A, B, C, D  
B = $ \begin{bmatrix} 1 & a & a2 \\ 1 & b & b2 \\ 1 & c & c2 \end{bmatrix} = 
\begin{bmatrix} 1 & a & a2 \\ 0 & b-a & (b-a)(b+a) \\ 0 & c-a & (c-a)(c+a) \end{bmatrix} = 
(b-a)(c-a)
\begin{bmatrix} 1 & a & a2 \\ 0 & 1 & b+a \\ 0 & 1 & c+a \end{bmatrix} =
\begin{bmatrix} 1 & a & a2 \\ 0 & 1 & b+a \\ 0 & 0 & c-b \end{bmatrix} $  
Det(B) = (b-a)(c-a)(c-b)

In [3]:
# 0 because not independent
Ar = np.matrix([
    [101, 201, 301],
    [102, 202, 302], 
    [103, 203, 303],
])
# 0 because not independent
Cr = np.matrix([[1,2,3]]).T @ np.matrix([[1,-4,5]])
# 0 because not independent
Dr = np.matrix([
    [0, 1, 3],
    [-1, 0, 4],
    [-3, -4, 0],
])
for m in Ar, Cr, Dr:
    _ = linear.det(m)

[[ 101.          201.          301.        ]
 [   0.           -0.99009901   -1.98019802]
 [   0.            0.            0.        ]]
-0.0
[[ 1. -4.  5.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
0.0
[[-1.  0.  4.]
 [ 0.  1.  3.]
 [ 0.  0.  0.]]
0.0


# Problem Set
If the entries
in every row of a square matrix A add to zero, solve Ax = 0 to prove that
det A = 0.  

A is singular (8)

If those entries add to one, show that det(A − I) = 0. Does this
mean that det A = 1?

If entries sum to 1, entries of A - I sum to 0, since 1 has been subtracted from each row.  
No. 

In [4]:
ap = np.matrix((
    [3,-2],
    [-2,3],
))
_ = linear.det(ap)

[[ 3.         -2.        ]
 [ 0.          1.66666667]]
5.0
