In [1]:
import numpy as np, linear, time

In [2]:
def makePerm(list_):
    if len(list_) == 1:
        return [list_]
    output = []
    for l in list_:
        temp = list_.copy()
        temp.remove(l)
        output.extend([[l]+perm for perm in makePerm(temp)])
    return output

# Recitation
A and B are 5 by 5 matrices  
A: x in diagonal, y in diagonal above, y in bottom left  

x^5. y can be eliminated by subtracting xy/x
Wrong. Cofactors, diagonal matrices, and transpose: x * x ** 4 + y * y ** 4 (


B: x in diagonal, y in other cells  
Subtract row above from each row. Add all right rows to each row
You end up with upper triangular, with (x + 4y)(x-y)^4

In [4]:
a = np.ones(10) + 2 * np.identity(10)
# print(a)
timey = time.time()
_ = linear.det(a)
print(time.time() - timey)
print(linear.det2(a))
print(time.time() - timey)

[[ 3.          1.          1.          1.          1.          1.          1.
   1.          1.          1.        ]
 [ 0.          2.66666667  0.66666667  0.66666667  0.66666667  0.66666667
   0.66666667  0.66666667  0.66666667  0.66666667]
 [ 0.          0.          2.5         0.5         0.5         0.5         0.5
   0.5         0.5         0.5       ]
 [ 0.          0.          0.          2.4         0.4         0.4         0.4
   0.4         0.4         0.4       ]
 [ 0.          0.          0.          0.          2.33333333  0.33333333
   0.33333333  0.33333333  0.33333333  0.33333333]
 [ 0.          0.          0.          0.          0.          2.28571429
   0.28571429  0.28571429  0.28571429  0.28571429]
 [ 0.          0.          0.          0.          0.          0.          2.25
   0.25        0.25        0.25      ]
 [ 0.          0.          0.          0.          0.          0.          0.
   2.22222222  0.22222222  0.22222222]
 [ 0.          0.          0.       

# Problem Set
## 1
Use 3 row swaps to get to identity, therefore -1^3 * 1 = -1

In [4]:
ap1 = np.matrix([
    [0,0,0,1],
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
])
_ = linear.det(ap1)
_ = linear.rrefIdentity(ap1)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
-1.0
Bottom half
[[ 0.  0.  0.  1.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]]
Divide
Top Half


## 2

In [ ]:
ap2 = np.matrix([
    [1,1,1,1],
    [1,2,3,4],
    [1,3,6,10],
    [1,4,10,19],
])
_ = linear.det(ap2)
output = linear.rrefIdentity(ap2)