In [1]:
import linear, numpy as np

# Recitation

In [2]:
ar = np.matrix([
    [2,2,-1],
    [1,3,0],
    [-1,1,4],
])
print(linear.det(ar)/6)
ar2 = ar.copy()
ar2[2,:] = [-201,-199,104]
print(linear.det(ar2)/6)

[[ 2.   2.  -1. ]
 [ 0.   2.   0.5]
 [ 0.   0.   3. ]]
12.0
2.0
[[ 2.   2.  -1. ]
 [ 0.   2.   0.5]
 [ 0.   0.   3. ]]
12.0
2.0


# Problem Set
## 1
Find C, det(A)  
If you change a1,3 = 4 to 100, why is det(A) unchanged?

Because it doesn't change diagonal matrix

In [6]:
ap1 = np.matrix([
    [1,1,4],
    [1,2,2],
    [1,2,5],
])
cp1 = linear.cofactor(ap1)
print(cp1)
print((ap1 @ cp1.T)[0,0])
_ = linear.det(ap1)

[[ 6. -3.  0.]
 [ 3.  1. -1.]
 [-6.  2.  1.]]
3.0
[[ 1.  1.  4.]
 [ 0.  1. -2.]
 [ 0.  0.  3.]]
3.0


## 2
Find the three by three matrix of partial derivatives:  
Simplify its determinant to J = ρ2 sin φ. 

x = r sin p cos t, y = r sin p sin t, z = r cos p   
$
\begin{bmatrix}
sin\ p\ cos\ t & r\ cos\ p\ cos\ t & - r\ sin\ p\ sin\ t \\
sin\ p\ sin\ t & r\ cos\ p\ sin\ t & r\ sin\ p\ cos\ t \\
cos\ p & - r\ sin\ p & 0 \\
\end{bmatrix} \\
$  
sin p cos t (r^2 sin^2 p cos t) - r cos p cos t (- r sin p cos p cos t) - r sin p sin t (- r sin^2 p sin t - r cos^2 p sin t)  
= r^2 sin^3 p cos^2 t + r^2 sin p cos^2 p cos^2 t + r^2 sin p sin^2 t  
= r^2 sin p (sin^2 p cos^2 t + cos^2 p cos^2 t + sin^2 t)  
= r^2 sin p (cos^2 t + sin^2 t)  
= r^2 sin p  