In [1]:
import linear, numpy as np

# Recitation
Answer: A2v = A(Av) = A(lv) = l(Av) = llv

A.I v = A.I * (Av/l) = v/l because Av = lv  
(A.I - I)v = v/l - v = (1/l - 1)v

(1-l)((1-l)(4-l) + 2)  
= (1-l)(l2 - 5l + 6)  
= (1-l)(l-3)(l-2)


In [2]:
ar = np.matrix([
    [1,2,3],
    [0,1,-2],
    [0,1,4]
])
eigenValues = [1, 2, 3]
print(linear.eigenVectors(ar, eigenValues))
print(linear.eigenVectors(ar @ ar, [e*e for e in eigenValues]))
print(linear.eigenVectors((ar.I - np.identity(3)), [1/e-1 for e in eigenValues]))

1 [[ 1. -0.  0.]] [[ 1.  0.  0.]] [[ 1.  0.  0.]]
2 [[-1. -2.  1.]] [[-2. -4.  2.]] [[-2. -4.  2.]]
3 [[ 0.5 -1.   1. ]] [[ 1.5 -3.   3. ]] [[ 1.5 -3.   3. ]]
[[ 1.  -1.   0.5]
 [-0.  -2.  -1. ]
 [ 0.   1.   1. ]]
1 [[ 1. -0.  0.]] [[ 1.  0.  0.]] [[ 1.  0.  0.]]
4 [[-1. -2.  1.]] [[-4. -8.  4.]] [[-4. -8.  4.]]
9 [[ 0.5 -1.   1. ]] [[ 4.5 -9.   9. ]] [[ 4.5 -9.   9. ]]
[[ 1.  -1.   0.5]
 [-0.  -2.  -1. ]
 [ 0.   1.   1. ]]
0.0 [[ 1.  0. -0.]] [[ 0.  0.  0.]] [[ 0.  0.  0.]]
-0.5 [[-1. -2.  1.]] [[ 0.5  1.  -0.5]] [[ 0.5  1.  -0.5]]
-0.6666666666666667 [[ 0.5 -1.   1. ]] [[-0.33333333  0.66666667 -0.66666667]] [[-0.33333333  0.66666667 -0.66666667]]
[[ 1.  -1.   0.5]
 [ 0.  -2.  -1. ]
 [-0.   1.   1. ]]


# Problem Set

## 1
A three by
three matrix B is known to have eigenvalues 0, 1 and 2. This information
is enough to find three of these (give the answers where possible):  
a) The rank of B  
Rank is 3 because singular matrices only have eigenvalues 0  
Wrong. Only singular matrices have 0 eigenvalues. Rank is 2  
b) The determinant of BTB  
det(B.T B) = det(B.T) det(B) = 0  
c) The eigenvalues of BTB  
Unknown  
d) The eigenvalues of (B2 + I)−1  
A^px = l^p x  
(B2+I)-1: 1/(e2+1)  

## 2
Find eigenvalues of A, B, C  
A: (1-l)((4-l)(6-l)-0): 1, 4, 6  
B: (3-l)(0-(2-l)(1-l)): 1, 2, 3  
C: 3(2-l)((2-l)(2-l)-(2-l)(2-l)): No eigenvalues  
Wrong  
C: (2-l)((2-l)(2-l)-4) - 2(2(2-l) - 4) + 2(4-2(2-l))
= (2-l)(2-l)(2-l) - 4(2-l) - 4(2-l) + 8 + 8 - 4(2-l)
= (2-l)3 - 12(2-l) + 16
Stuck

In [4]:
ap = np.matrix([
    [1,2,3],
    [0,4,5],
    [0,0,6],
])
bp = np.matrix([
    [0,0,1],
    [0,2,0],
    [3,0,0],
])
cp = np.matrix([
    [2,2,2],
    [2,2,2],
    [2,2,2],
])
aep = [1,4,6]
bep = [-np.sqrt(3),2,np.sqrt(3)]
cep = [0,6]
for letter in 'abc':
    linear.eigenVectors(eval(letter+'p'), eval(letter+'ep'))

1 [[ 1. -0. -0.]] [[ 1.  0.  0.]] [[ 1.  0.  0.]]
4 [[ 0.66666667  1.         -0.        ]] [[ 2.66666667  4.          0.        ]] [[ 2.66666667  4.          0.        ]]
6 [[ 1.6  2.5  1. ]] [[  9.6  15.    6. ]] [[  9.6  15.    6. ]]
-1.73205080757 [[-0.57735027 -0.          1.        ]] [[ 1.          0.         -1.73205081]] [[ 1.          0.         -1.73205081]]
2 [[ 0.  1.  0.]] [[ 0.  2.  0.]] [[ 0.  2.  0.]]
1.73205080757 [[ 0.57735027 -0.          1.        ]] [[ 1.          0.          1.73205081]] [[ 1.          0.          1.73205081]]
0 [[-1.  1.  0.]] [[ 0.  0.  0.]] [[ 0.  0.  0.]]
0 [[-1.  0.  1.]] [[ 0.  0.  0.]] [[ 0.  0.  0.]]
6 [[ 1.  1.  1.]] [[ 6.  6.  6.]] [[ 6.  6.  6.]]
