In [1]:
import linear, numpy as np

# Lecture
## Fibonacci Sequence
Fk+2 = Fk+1 + Fk  
Fk+1 = Fk+1  
Let u = [Fk+1, Fk]  
Matrix is al  
## Eigenvalues
(1-l)-l - 1 = l2 - l -1 = 0  
l = (1 +- sqrt5)/2  

In [2]:
al = np.matrix([
    [1,1],
    [1,0],
])
el = (1 - np.sqrt(5))/2, (1 + np.sqrt(5))/2
ul = np.matrix([1,0]).T
for k in range(10):
    print(linear.aku0(al, el, linear.diagonal, ul, k)[0,0].round(0))

1.0
1.0
2.0
3.0
5.0
8.0
13.0
21.0
34.0
55.0


# Recitation
Find a formula for $C^k$ where  
$ C = \begin{bmatrix} 2b - a & a - b \\ 2b - 2a & 2a - b \end{bmatrix} $  
Find $C^{100}$ where $a = b = -1$  
## Eigenvalues
$(2b-a-l)(2a-b-l) - (2b-2a)(a-b) = 0 \\
= (4ab - 2a^2 - 2al - 2b^2 + ab + bl - 2bl + al + l^2) - (2ab - 2a^2 - 2b^2 + 2ab) = 0 \\
= 4ab + ab - 2ab - 2ab - 2a^2 + 2a^2 - 2al + al - 2b^2 + 2b^2 + bl - 2bl + l^2 \\
= ab - al - bl + l^2 \\
= (l-a)(l-b) \\
l = a, b $  
## Eigenvectors
$ \begin{bmatrix} 2b - 2a & a - b \\ 2b - 2a & a - b \end{bmatrix} 
= \begin{bmatrix} 1 & -0.5 \\ 0 & 0 \end{bmatrix} \\
\begin{bmatrix} b - a & a - b \\ 2b - 2a & 2a - 2b \end{bmatrix} 
= \begin{bmatrix} 1 & -1 \\ 0 & 0 \end{bmatrix} \\
S = \begin{bmatrix} 0.5 & 1 \\ 1 & 1 \end{bmatrix} \\
L = \begin{bmatrix} a & 0 \\ 0 & b \end{bmatrix} $

In [3]:
a, b = -1, -1
sr = np.matrix([
    [0.5, 1],
    [1,1],
])
print(sr @ linear.diagonal([a,b], 100) @ sr.I)
print(sr.I)

[[ 1.  0.]
 [ 0.  1.]]
[[-2.  2.]
 [ 2. -1.]]


# Problem Set
## 1
Describe all matrices S that diagonalize this matrix A (find all eigenvectors)  
$ \begin{bmatrix} 4 & 0 \\ 1 & 2 \end{bmatrix} $  
(4-l)(2-l) = 0  
l = 4, 2  
Then describe all matrices that diagonalize A.I.  
Ax = lx  
A.Ix = A.I (Ax/l) = x/l  
Same matrices, different lambda  

In [4]:
ap1 = linear.toMatrix('$ \begin{bmatrix} 4 & 0 \\ 1 & 2 \end{bmatrix} $')
ep1 = [2,4]
sp1 = linear.eigenVectors(ap1, ep1)
print(sp1)

2 [[-0.  1.]] [[ 0.  2.]] [[ 0.  2.]]
4 [[ 2.  1.]] [[ 8.  4.]] [[ 8.  4.]]
[[-0.  2.]
 [ 1.  1.]]


## 2
Find Λ and S to diagonalize A:  
$ \begin{bmatrix} .6 & .9 \\ .4 & .1 \end{bmatrix} \\
(0.6 - l)(0.1 - l) - 0.36 = 0  \\
0.06 - 0.1l - 0.6l + l^2 - 0.36 = 0  \\
l^2 - 0.7l - 0.3 = 0 \\
(l-1)(l+0.3) = 0 \\
l = 1, -0.3$  

In [3]:
ap2 = linear.toMatrix('$ \begin{bmatrix} .6 & .9 \\ .4 & .1 \end{bmatrix} $')
ep2 = [1,-0.3]
sp2 = linear.eigenVectors(ap2, ep2)
print(sp2)
print(linear.diagonal(ep2))
print(sp2 @ linear.diagonal(ep2, 1000) @ sp2.I)

1 [[ 2.25  1.  ]] [[ 2.25  1.  ]] [[ 2.25  1.  ]]
-0.3 [[-1.  1.]] [[ 0.3 -0.3]] [[ 0.3 -0.3]]
[[ 2.25 -1.  ]
 [ 1.    1.  ]]
[[ 1.   0. ]
 [ 0.  -0.3]]
[[ 0.69230769  0.69230769]
 [ 0.30769231  0.30769231]]
