In [1]:
import linear, numpy as np

# 1
Suppose q1, q2, q3 are orthonormal vectors in R3. Find all possible values
for these 3 by 3 determinants and explain your thinking in 1 sentence each. 
a. det(q1, q2, q3)  
1 or -1 because it is a rotated cube with side 1  
b. 2 or -2, because  
c. det(q1,q2,q3) @ det(q2*q3*q1)  
It is either -1 @ -1 or 1 * 1, because it is the same matrix with two columns flipped.  

In [3]:
a = np.matrix([
    [1,0,1],
    [1,1,0],
    [0,1,1],
])
print(linear.det(a))

[[ 1.  0.  1.]
 [ 0.  1. -1.]
 [ 0.  0.  2.]]
2.0


# 2
Suppose we take measurements at the 21 equally spaced times t = −10, −9, . . . , 9, 10.
All measurements are bi = 0 except that b11 = 1 at the middle time t = 0.  
(a) Using least squares, what are the best C and D to fit those 21 points
by a straight line C + Dt ?  
C = 0.0476, D = 0  
(b) You are projecting the vector b onto what subspace ? (Give a basis.)  
Column space. Column of 1's plus column of t is basis  
Find a nonzero vector perpendicular to that subspace.  
b - ax

In [20]:
a2 = np.matrix([
    [1] * 21,
    list(range(-10, 11)),
]).T
b2 = np.matrix([0] * 10 + [1] + [0] * 10).T
x2 = (a2.T @ a2).I @ a2.T @ b2
projection = a2 @ x2
print((b2 - projection).T @ projection, x2)

[[ -1.73472348e-18]] [[ 0.04761905]
 [ 0.        ]]


# 3
The Gram-Schmidt method produces orthonormal vectors q1, q2, q3
from independent vectors a1, a2, a3 in R5. Put those vectors into the columns
of 5 by 3 matrices Q and A. 

(a) Give formulas using Q and A for the projection matrices PQ and PA
onto the column spaces of Q and A.

PA = A @ (A.T @ A).I @ A.T  
PQ = Q @ Q.T  

(b) Is PQ = PA and why ? What is PQ times Q ? What is det PQ ?

PQ is PA because Q and A occupy the same subspace.  
PQ @ Q = Q because Q is already in subspace of Q.  
det PQ =  

Stuck

Non identity projections are always singular because not enough dimensions. 

(c) Suppose a4 is a new vector and a1, a2, a3, a4 are independent. Which of
these (if any) is the new Gram-Schmidt vector q4 ? (PA and PQ from
above)

2  

Wrong. It is 3

# 4
Suppose a 4 by 4 matrix has the same entry × throughout its first row and
column. The other 9 numbers could be anything like 1, 5, 7, 2, 3, 99, π, e, 4.  

(a) The determinant of A is a polynomial in ×. What is the largest
possible degree of that polynomial ? Explain your answer.  

Stuck

2, because each term can only have 1 entry from each row and each column

b. If those 9 numbers give the identity matrix I, what is det A ? Which
values of × give det A = 0 ?  

Divide first column by x, subtract other columns from column 1, so that other cells of first column are 0. 