In [1]:
import linear, numpy as np

In [2]:
a = np.matrix([
    [2,-1,0],
    [-1,2,-1],
    [0,-1,2],
])
print(linear.pivots(a))

[[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.          1.33333333]]
[ 2.          1.5         1.33333333]


# Recitation
br is positive definite if c > 0, positive semidefinite if c == 0  
c is added to bottom right of matrix

In [8]:
br = np.matrix([
    [2,-1,-1],
    [-1,2,-1],
    [-1,-1,2],
])
print(linear.pivots(br))

[[ 2.  -1.  -1. ]
 [ 0.   1.5 -1.5]
 [ 0.   0.   0. ]]
[ 2.   1.5]


# Problem Set
When A and
B are symmetric positive definite, AB might not even be symmetric, but its
eigenvalues are still positive. Start from ABx = λx and take dot products
with Bx. Then prove λ > 0. 

ABx = lx  
(ABx).T Bx = (lx).T Bx  
(Bx).T A.T Bx = lxT Bx  
(Bx).T A (Bx) = l(xTBx)  

(Bx).T A Bx > 0 because A is positive definite, and Bx is just like x  
x.T B X > 0 because B is positive definite  
Therefore l = positive / positive = positive

Find the quadratic form associated with the matrix. 
Is this function f(x, y) always positive, always negative, or sometimes
positive and sometimes negative?  

Always negative.  
= x + 12xy + 9y2 
= (x+6y)2 - 27y2

In [11]:
ap2 = np.matrix([
    [1,5],
    [7,9],
])
print(linear.pivots(ap2))

[[  1.   5.]
 [  0. -26.]]
[[  1. -26.]]
