In [1]:
import linear, numpy as np

# Recitation

In [2]:
def temp(a):
    matrices = linear.svd(a)
    for m in matrices:
        print(m)
    print()
    print(a @ matrices[2].T)
    print(matrices[0] @ matrices[1])
    print()

ar = np.matrix([
    [5, 5],
    [-1, 7],
])
temp(ar)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[ 8.94427191  0.        ]
 [ 0.          4.47213595]]
[[ 0.31622777  0.9486833 ]
 [-0.9486833   0.31622777]]

[[ 6.32455532 -3.16227766]
 [ 6.32455532  3.16227766]]
[[ 6.32455532 -3.16227766]
 [ 6.32455532  3.16227766]]



# Problem Set

Calculate the singular value decomposition A = UΣVT of the
Fibonacci matrix

In [6]:
ap1 = np.matrix([
    [1,1],
    [1,0],
])
temp(ap1)

[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
[[ 1.61803399  0.        ]
 [ 0.          0.61803399]]
[[ 0.85065081  0.52573111]
 [-0.52573111  0.85065081]]

[[ 1.37638192  0.3249197 ]
 [ 0.85065081 -0.52573111]]
[[ 1.37638192 -0.3249197 ]
 [ 0.85065081  0.52573111]]



Suppose A has orthogonal columns w1, w2, ..., wn
of lengths σ1, σ2, ..., σn. Calculate ATA. What are U, Σ, and V in the SVD?
$ 
A = \begin{bmatrix} w11 & w21 \\ w12 & w22 \end{bmatrix} \\
AT = \begin{bmatrix} w11 & w12 \\ w21 & w22 \end{bmatrix} \\
ATA = \begin{bmatrix} w1w1 & w1w2 \\ w2w1 & w2w2 \end{bmatrix}
= \begin{bmatrix} σ12 & 0 \\ 0 & σ22 \end{bmatrix} \\
V = I, S = diag(σ1, σ2) \\
AV = US \\
ATU = S: \begin{bmatrix} w1u1 & w1u2 \\ w2u1 & w2u2 \end{bmatrix}
= \begin{bmatrix} σ1 & 0 \\ 0 & σ2 \end{bmatrix}
$  
Therefore u1 = w1/σ, u2 = w2/σ
