In [2]:
import linear, numpy as np

# Lecture

In [3]:
def lecture(a):
    print('a')
    print(a)
    # Eigenvectors of a (a basis)
    s = linear.eigenVectors(a, linear.eigen2x2(a), 'Silent')
    print('eigenvectors')
    print(s)
    # Transformation
    t = a @ s
    print('t = a @ s')
    print(t)
    # Find a by inverting basis
    print('a = t @ s.I')
    print(t @ s.I)
    # Find eigenvalues through finding L
    print('L')
    print((s.I @ a @ s).round(2))
    # Find eigenvalues directly
    print('eigenvalues')
    print(linear.eigen2x2(a))

In [4]:
# x is a vector
x = np.matrix([1,1]).T
# a is a projection matrix based on x
a = x @ (x.T @ x).I @ x.T
lecture(a)

a
[[ 0.5  0.5]
 [ 0.5  0.5]]
eigenvectors
[[ 1. -1.]
 [ 1.  1.]]
t = a @ s
[[ 1.  0.]
 [ 1.  0.]]
a = t @ s.I
[[ 0.5  0.5]
 [ 0.5  0.5]]
L
[[ 1.  0.]
 [ 0.  0.]]
eigenvalues
[ 1.  0.]


In [5]:
# x is a vector
x = np.matrix([1,0]).T
# a is a projection matrix based on x
a = x @ (x.T @ x).I @ x.T
lecture(a)

a
[[ 1.  0.]
 [ 0.  0.]]
eigenvectors
[[ 1. -0.]
 [ 0.  1.]]
t = a @ s
[[ 1.  0.]
 [ 0.  0.]]
a = t @ s.I
[[ 1.  0.]
 [ 0.  0.]]
L
[[ 1.  0.]
 [ 0.  0.]]
eigenvalues
[ 1.  0.]


# Recitation
Let T(A) = A.T where A is 2x2  
1. Why is T linear? What is T.I?  
Because T(A+B) = T(A)+T(B), T(cA) = cT(A). T.I is T, because T.I T = I  
2. Write down the matrix of T  
3. Eigenvalues/eigenvectors of T?  

In [6]:
t = np.matrix([
    [1,0,0,0],
    [0,0,1,0],
    [0,1,0,0],
    [0,0,0,1],
])
w = np.matrix([
    [1,0,0,0],
    [0,0,0,1],
    [0,1,1,0],
    [0,1,-1,0],
]).T
print(w)
t2 = np.matrix([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,-1],
])

[[ 1  0  0  0]
 [ 0  0  1  1]
 [ 0  0  1 -1]
 [ 0  1  0  0]]


# Problem Set
## 1
Consider the transformation T that doubles the distance
between each point and the origin without changing the direction from
the origin to the points. In polar coordinates this is described by
T(r, θ) = (2r, θ).  
a. IS T a linear transformation?  
Yes, because T(u+v) = T(u) + T(v) and T(cu) = cT(u)  
b. Describe T using Cartesian (xy) coordinates. Check your work by confirming that the transformation doubles the lengths of vectors.  
T(x,y) = 2x, 2y  
c. If your answer to (a) was ”yes”, find the matrix of T. If your answer to
(a) was ”no”, explain why the T isn’t linear.  

In [7]:
sp1 = np.matrix([
    [1,0],
    [0,1],
])
tp1 = np.matrix([
    [2,0],
    [0,2],
])
print(tp1 @ sp1.I)

[[ 2.  0.]
 [ 0.  2.]]


## 2
Describe a transformation which leaves the zero vector
fixed but which is not a linear transformation.  
T(x,y) = x, |y|; x, y^2