In [1]:
import linear, numpy as np

# Recitation
The vector space of all polynomials in x of degree <= 2 has a basis 1, x, x2.  
Let w1 be a different basis of polynomials whose values at x = -1, 0, 1 are given by:  
$ \begin{bmatrix} 
x & w1 & w2 & w3 & y & 1 & x & x2\\ 
-1 & 1 & 0 & 0 & 6 & 1 & -1 & 1\\ 
0 & 0 & 1 & 0 & 5 & 1 & 0 & 0\\
1 & 0 & 0 & 1 & 4 & 1 & 1 & 1
\end{bmatrix} $  
a. Express y(x) = -x + 5 in this basis  
$ \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} 
\begin{bmatrix} a \\ b \\ c \end{bmatrix} = \begin{bmatrix} 6 \\ 5 \\ 4 \end{bmatrix} $  
a, b, c = 6, 5, 4  
b. Find the change of basis matrices  
$ a: \begin{bmatrix} 1 & -1 & 1 \\ 1 & 0 & 0 \\ 1 & 1 & 1 \end{bmatrix} 
\begin{bmatrix} 1 \\ x \\ x2 \end{bmatrix} = \begin{bmatrix} w1 \\ w2 \\ w3 \end{bmatrix} \\
a.I: \begin{bmatrix} 0 & 1 & 0 \\ -0.5 & 0 & 0.5 \\ 0.5 & -1 & 0.5 \end{bmatrix} 
\begin{bmatrix} w1 \\ w2 \\ w3 \end{bmatrix} = \begin{bmatrix} 1 \\ x \\ x2 \end{bmatrix}$  
c. Find the matrix of taking derivatives in both bases  
$ d: \begin{bmatrix} 0 & 1 & 0 \\ 0 & 0 & 2 \\ 0 & 0 & 0 \end{bmatrix} 
\begin{bmatrix} 1 \\ x \\ x2 \end{bmatrix} = \begin{bmatrix} 1 \\ x \\ x2 \end{bmatrix} $  

In [2]:
a = linear.toMatrix('$ \begin{bmatrix} 1 & -1 & 1 \\ 1 & 0 & 0 \\ 1 & 1 & 1 \end{bmatrix} $')
d = linear.toMatrix('$ \begin{bmatrix} 0 & 1 & 0 \\ 0 & 0 & 2 \\ 0 & 0 & 0 \end{bmatrix} $')
print(a @ d @ a.I)

[[-1.5  2.  -0.5]
 [-0.5  0.   0.5]
 [ 0.5 -2.   1.5]]


# Problem Set
Verify that the vectors of the Haar wavelet basis, given in
lecture, are orthogonal. Adjust their lengths so that the resulting basis
vectors are orthonormal.

In [5]:
ap1 = np.matrix([
    [1,1,1,1,1,1,1,1],
    [1,1,1,1,-1,-1,-1,-1],
    [1,1,-1,-1,0,0,0,0],
    [0,0,0,0,1,1,-1,-1],
    [1,-1,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,-1],
]).T
ap1n = linear.normalise(ap1)
print((ap1n.T @ ap1n).round(2))

[[ 1. -0.  0.  0.  0.  0.]
 [-0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


We can think of the set of all two by two matrices with
real valued entries as a vector space. Describe two different bases for this
space. Is one of your bases better than the other for describing diagonal
matrices? What about triangular matrices? Symmetric matrices?