In [5]:
import linear, numpy as np

In [6]:
a = np.matrix([
    [5,1],
    [2,0],
])
# print(linear.multiplyR(linear.svd(a)).round(2))
print(linear.pseudoI(a).round(2))
print(a.I)

[[ 0.   0.5]
 [ 1.  -2.5]]
[[ 0.   0.5]
 [ 1.  -2.5]]


# Recitation
What is a+ (pseudo inverse)?  
What is aa+, a+a?  
If x is in n(a), what is a+ax?  
0, because ax = 0, and a+0 = 0

In [7]:
a = np.matrix([1, 2])
ap = linear.pseudoI(a)
print(ap)
print(a @ ap)
print(ap @ a)
print(ap @ a @ linear.nullSpace(a))
print(ap @ a @ a.T)

[[ 0.2]
 [ 0.4]]
[[ 1.]]
[[ 0.2  0.4]
 [ 0.4  0.8]]
[[ 0.]
 [ 0.]]
[[ 1.]
 [ 2.]]


# Problem Set
Find a right inverse for ap1  
Does the matrix ap2 have a left/right/pseudoinverse?  

In [8]:
ap1 = np.matrix([
    [1,0,1],
    [0,1,0],
])
print(ap1 @ linear.rightI(ap1))
ap2 = np.matrix([
    [4,3],
    [8,6],
])
# print(linear.leftI(ap2))
# print(linear.rightI(ap2))
print(linear.pseudoI(ap2) @ ap2 @ ap2.T)
print(linear.pseudoI(ap2) @ ap2 @ linear.nullSpace(ap2))

[[ 1.  0.]
 [ 0.  1.]]
[[ 4.  8.]
 [ 3.  6.]]
[[ 0.]
 [ 0.]]
