In [1]:
import linear, numpy as np

In [2]:
a = np.matrix([
    [1,1],
    [1,0],
])
u0 = np.matrix([1,0]).T
eigenValues = linear.eigen2x2(a)
s = linear.eigenVectors(a, eigenValues, 'Silent')
c = s.I @ u0
print(eigenValues)
print(s)
print(c)
print(s @ linear.diagonal(eigenValues, 10) @ s.I @ u0)
print(s @ linear.diagonal(eigenValues, 10) @ c)

[ 1.61803399 -0.61803399]
[[ 1.61803399 -0.61803399]
 [ 1.          1.        ]]
[[ 0.4472136]
 [-0.4472136]]
[[ 89.]
 [ 55.]]
[[ 89.]
 [ 55.]]


# Recitation
For projection matrices P(A), eigenvalues are 1 and 0, eigenvectors are column space and left nullspace of A

In [8]:
ar1 = np.matrix([3,4]).T
pr1 = linear.projection(ar1)
er1 = linear.eigen2x2(pr1)
evr1 = linear.eigenVectors(pr1, er1)
print(linear.leftNullSpace(ar1))

Arrays
[[3]
 [4]]
[[ 0.04]]
[[3 4]]
Multiply
[[3]
 [4]]
[[ 0.12]
 [ 0.16]]
[[ 0.36  0.48]
 [ 0.48  0.64]]
1.0 [[ 0.75  1.  ]] [[ 0.75  1.  ]] [[ 0.75  1.  ]]
0.0 [[-1.33333333  1.        ]] [[ 0.  0.]] [[  0.00000000e+00   1.11022302e-16]]
[[ 1.   -0.75]]


In [4]:
ar2 = np.matrix([
    [0.6, -0.8],
    [0.8, 0.6],
])
er2 = linear.eigen2x2(ar2)
evr2 = linear.eigenVectors(ar2, er2)

(0.6+0.8j) [[ 0.+1.j  1.+0.j]] [[-0.8+0.6j  0.6+0.8j]] [[-0.8+0.6j  0.6+0.8j]]
(0.6-0.8j) [[-0.-1.j  1.+0.j]] [[-0.8-0.6j  0.6-0.8j]] [[-0.8-0.6j  0.6-0.8j]]


In [6]:
ar3 = 2 * pr1 - np.identity(2)
print(ar3)
er3 = linear.eigen2x2(ar3)
evr3 = linear.eigenVectors(ar3, er3)

[[-0.28  0.96]
 [ 0.96  0.28]]
1.0 [[ 0.75  1.  ]] [[ 0.75  1.  ]] [[ 0.75  1.  ]]
-1.0 [[-1.33333333  1.        ]] [[ 1.33333333 -1.        ]] [[ 1.33333333 -1.        ]]
