In [12]:
import linear, numpy as np
def print_(inputString):
    print(inputString)
    print(eval(inputString))

# 1
## a
If a square matrix A has all n of its singular values equal to 1 in the SVD, what basic class of matrices does A belong to? (singular, symmetric, orthogonal, positive definite or semidefinite, diagonal). 

A is orthogonal, because singular values equal 1 when A.T A = I, which only happens if A is orthogonal. 

In [13]:
a = np.matrix([
    [1,0],
    [0,1],
])
print_('linear.eigen2x2(a)')

linear.eigen2x2(a)
[ 1.  1.]


## b
Given S and L, write B as the product of 3 specific matrices.  
S @ L @ S.I  

Write C = (B+I).I as the product of 3 matrices  
C = S @ 1/(L + I) @ S.I  

What classes do B and C belong to.  
B: symmetric, positive semidefinite, diagonal  
Missed singular  
C: symmetric, positive definite, diagonal  

In [14]:
H = 0.5 * np.matrix([
    [1,1,-1,-1],
    [1,-1,-1,1],
    [1,1,1,1],
    [1,-1,1,-1],
])
E = [0,1,2,3]
B = H @ linear.diagonal(E) @ H.I
print_('B')
print_('linear.eigenVectors(B, E)')
print_('B @ B.T')

print_('(B + np.identity(4)).I')
E2 = [1/(e + 1) for e in E]
print_('E2')
C = H @ linear.diagonal(E2) @ H.I
print_('C')
print_('C @ C.T')

B
[[ 1.5 -0.5 -1.   0. ]
 [-0.5  1.5  0.  -1. ]
 [-1.   0.   1.5 -0.5]
 [ 0.  -1.  -0.5  1.5]]
linear.eigenVectors(B, E)
0 [[ 1.  1.  1.  1.]] [[ 0.  0.  0.  0.]] [[ 0.  0.  0.  0.]]
1 [[-1.  1. -1.  1.]] [[-1.  1. -1.  1.]] [[-1.  1. -1.  1.]]
2 [[-1. -1.  1.  1.]] [[-2. -2.  2.  2.]] [[-2. -2.  2.  2.]]
3 [[ 1. -1. -1.  1.]] [[ 3. -3. -3.  3.]] [[ 3. -3. -3.  3.]]
[[ 1. -1. -1.  1.]
 [ 1.  1. -1. -1.]
 [ 1. -1.  1. -1.]
 [ 1.  1.  1.  1.]]
B @ B.T
[[ 3.5 -1.5 -3.   1. ]
 [-1.5  3.5  1.  -3. ]
 [-3.   1.   3.5 -1.5]
 [ 1.  -3.  -1.5  3.5]]
(B + np.identity(4)).I
[[ 0.52083333  0.14583333  0.22916667  0.10416667]
 [ 0.14583333  0.52083333  0.10416667  0.22916667]
 [ 0.22916667  0.10416667  0.52083333  0.14583333]
 [ 0.10416667  0.22916667  0.14583333  0.52083333]]
E2
[1.0, 0.5, 0.3333333333333333, 0.25]
C
[[ 0.52083333  0.14583333  0.22916667  0.10416667]
 [ 0.14583333  0.52083333  0.10416667  0.22916667]
 [ 0.22916667  0.10416667  0.52083333  0.14583333]
 [ 0.10416667  0.22916667  0.1

# 2. 
Find the eigenvalues and eigenvectors of A  
(-1 - L) * -L(1-L) = 0  
(1+L) * L(1-L) = 0  
L = [-1, 0, 1]  

Explain why A^1001 = A. Is A^1000 I?  
A^1001 = A because A = SL^k S.I * I and L^k = L.  
A^1000 does not equal I because L^1000 != I  

How many eigenvalues of A.T A are positive? zero? negative? Does A.T A have the same eigenvalues as A?  
2 Positive and 1 0. No

In [20]:
A = np.matrix([
    [-1,2,4],
    [0,0,5],
    [0,0,1],
])
E = [-1, 0, 1]
S = linear.eigenVectors(A, E)
print_('S')
print_('S.I')
print_('linear.aku0(A, E, linear.diagonal, np.identity(3), 1001)')
E2 = linear.diagonalExp(E)
print_('E2')
print_('linear.aku0(A, E, linear.diagonalExp, np.identity(3), 1)')

-1 [[ 1. -0. -0.]] [[-1.  0.  0.]] [[-1.  0.  0.]]
0 [[ 2.  1. -0.]] [[ 0.  0.  0.]] [[ 0.  0.  0.]]
1 [[ 7.  5.  1.]] [[ 7.  5.  1.]] [[ 7.  5.  1.]]
S
[[ 1.  2.  7.]
 [-0.  1.  5.]
 [-0. -0.  1.]]
S.I
[[ 1. -2.  3.]
 [ 0.  1. -5.]
 [ 0.  0.  1.]]
linear.aku0(A, E, linear.diagonal, np.identity(3), 1001)
[[-1.  2.  4.]
 [ 0.  0.  5.]
 [ 0.  0.  1.]]
E2
[[ 0.36787944  0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.          2.71828183]]
linear.aku0(A, E, linear.diagonalExp, np.identity(3), 1)
[[  0.36787944   1.26424112  10.13161112]
 [  0.           1.           8.59140914]
 [  0.           0.           2.71828183]]


In [5]:
_ = linear.rref(A.T @ A)

Bottom half
[[  1.  -2.  -4.]
 [ -2.   4.   8.]
 [ -4.   8.  42.]]
[[  1.  -2.  -4.]
 [  0.   0.   0.]
 [  0.   0.  26.]]
[[  1.  -2.  -4.]
 [  0.   0.  26.]
 [  0.   0.   0.]]
Top Half
[[ 1. -2. -4.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 1. -2.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


# 3
A has orthonormal eigenvectors and positive eigenvalues.  

a. What are the eigenvalues and eigenvectors of A.I?  
Eigenvalues are same. Eigenvectors are the same. 

b. b is a combination of the eigenvectors. What is a quick formula for c1?  
b = Qc (b is in Q's column space)  
c = Q.Ib = Q.Tb (c is in Q's row space)
Therefore c1 = q1.T b

c. A.I b = combination of the eigenvectors. What is a quick formula for d?  
A.I b = Qd  
d = Q.I A.Ib = Q.T A.I b  
Therefore d1 = q1.T A.I b  

d = c1/l1