In [13]:
import linear, numpy as np
def print_(inputString):
    print(inputString)
    print(eval(inputString))

# 1
A = 3x4. Ax = 0 has 2 special solutions.  
Find all subspaces.  

Correct

In [14]:
a1 = np.matrix([
    [1,0,-1,2],
    [0,1,-1,1],
    [0,0,0,0],
])
print_('linear.columnSpace(a1)')
print_('linear.rowSpace(a1)')
print_('linear.leftNullSpace(a1)')
print_('linear.nullSpace(a1)')

linear.columnSpace(a1)
[[1 0]
 [0 1]
 [0 0]]
linear.rowSpace(a1)
[[ 1.  0. -1.  2.]
 [ 0.  1. -1.  1.]]
linear.leftNullSpace(a1)
[[ 0.  0.  1.]]
linear.nullSpace(a1)
[[ 1. -2.]
 [ 1. -1.]
 [ 1.  0.]
 [ 0.  1.]]


# 2
Find the inverse of an upper triangular matrix with nonzero entries a,b,c,d,e,f  
$ \begin{bmatrix} 1 & -b/ad & -c/af + be/adf \\ 0 & 1/d & -e/df \\ 0 & 0 & 1/f \end{bmatrix} $  

Correct

Suppose U is eigenvectors of A. Show that A is also upper triangular.  

Wrong  
A = ULU.I
U, L, U.I are upper triangular, therefore A is upper triangular. 

Explain why U can't be U in SVD  

Wrong  
U is not orthogonal

In [15]:
u2 = np.matrix([
    [1,2,3],
    [0,4,5],
    [0,0,6],
])
_ = linear.rrefIdentity(u2)

Bottom half
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  4.  5.  0.  1.  0.]
 [ 0.  0.  6.  0.  0.  1.]]
Top Half
[[ 1.          2.          3.          1.          0.          0.        ]
 [ 0.          1.          1.25        0.          0.25        0.        ]
 [ 0.          0.          1.          0.          0.          0.16666667]]
[[ 1.          2.          0.          1.          0.         -0.5       ]
 [ 0.          1.          0.          0.          0.25       -0.20833333]
 [ 0.          0.          1.          0.          0.          0.16666667]]
[[ 1.          0.          0.          1.         -0.5        -0.08333333]
 [ 0.          1.          0.          0.          0.25       -0.20833333]
 [ 0.          0.          1.          0.          0.          0.16666667]]


# 3
A and B have the same number of rows.  
What can you say about the comparison between A and [A B]  
Rank of [A B] >= rank of A because [A B] might have additional pivots not in A. If not, rank of [A B] still = rank of A  

Correct

Suppose B = A2. How do these ranks compare.  
Columns of A2 = combination of columns of A, therefore A2's columnspace is inside A's columnspace.   Therefore columnspace of [A A2] = columnspace of A, therefore rank [A A2] = rank of A  

Correct

If A is m by n of rank r, what are the dimensions of nullspace(a), nullspace([a a])  
nullspace of A = n x (m - r). nullspace of [A A] = 2n x (m - r)  

Wrong.  
Should be n-r, 2n-r

# 4
Suppose A is a 5 by 3 matrix, and has no nullspace

What can you say about the columns of A?  
They are independent. 

Why is A.T Ax also 0?  
x.T A.T Ax = |Ax| = 0. Since every element of |Ax| >= 0, Ax must = 0  

Why is B = (A.T A).I A.T is a one sided inverse of A?
It is a left inverse because BA = (A.T A).I A.T A = I (A.T A times its inverse)  
It is not a right inverse because A (A.T A).I A.T != I  

Correct

# 5
If A is 3x3 positive definite, then Aq = lq  
Suppose x = qc  

What is x.T x?  
x.T x = c.T q.T q c = c.T c = c12 + c22 + c32

Correct

What is x.T ax?  
x.T ax = c.T q.T a qc  
= c.T q.T @ l1c1q1 + l2c2q2 + l3c3q3
= l1c12 + l2c22 + l3c32

Correct

What c would make x.T ax / x.T x as big as possible?  
c does not affect the ratio  

Wrong  
Don't understand why c1 and c2 have to be 0. 

# 6
Find a linear combination of vectors v and u that is perpendicular to u  
u.T (v - ux) = 0  
u.T v = u.T u x  
x = u.T v / u.T u  
w = v - u u.T v / u.T u  

Correct

For A = [u v], find Q, R
Orthogonal = [o1 o2] = [u, v - u u.T v / u.T u]
Q = [o1/|o1| o2/|o2|]  
A = QR => R = Q.T A

Wrong.  
Missing derivation of R  
Don't understand why w.T v / |w| = |w|

Find projection matrix P  
P = Q Q.T  

Correct

# 7
Find the eigenvalues if c, c2  

Wrong.  
C: l^4 - 1 = 0; C2: l^2 = 1

Inverses = c.T, c2.T  
Determinants = -1, 0, 15  

Correct

In [49]:
c = np.matrix([
    [0,0,0,1],
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
])
c2 = c @ c
_ = linear.rrefIdentity(c)
_ = linear.rrefIdentity(c2)
for r in range(3):
    print(r)
    print(linear.det(c+r*np.identity(4)))

Bottom half
[[ 0.  0.  0.  1.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]]
Top Half
Bottom half
[[ 0.  0.  1.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1

# 8
Suppose a rectangular matrix A has independent columns

a. How do you find the best least squares xhat for Ax = b? Find xhat and p.  
xhat = (A.T A).I A.T b
p = Axhat

p is in columnspace. e is in left nullspace

Correct

In [21]:
a = np.matrix([
    [1,0],
    [3,0],
    [0,-1],
    [0,-3],
])

print(a @ (a.T @ a).I @ a.T)

[[ 0.1  0.3  0.   0. ]
 [ 0.3  0.9  0.   0. ]
 [ 0.   0.   0.1  0.3]
 [ 0.   0.   0.3  0.9]]


# 9
This question is about the matrices A with 3 on the main diagonal, 2 on the diagonal above, 1 on the diagonal below.  

What are the determinants of A2 and A3?  
D = 3 * Dn-1 - 2 * Dn-2  

Correct

In [47]:
def buildMatrix(n):
    a = np.asmatrix(np.zeros([n, n]))
    for r in range(n):
        a[r,r] = 3
    for r in range(n-1):
        a[r+1,r] = 1
        a[r,r+1] = 2
    return a

for r in range(0, 6):
    print(r)
    print(buildMatrix(r))
    print(buildMatrix(r)[1:,[c for c in range(r) if c != 1]])
#     print(linear.cofactor(buildMatrix(r)))
    print(linear.det(buildMatrix(r), 'Silent'))

0
[]
[]
1
1
[[ 3.]]
[]
3.0
2
[[ 3.  2.]
 [ 1.  3.]]
[[ 1.]]
7.0
3
[[ 3.  2.  0.]
 [ 1.  3.  2.]
 [ 0.  1.  3.]]
[[ 1.  2.]
 [ 0.  3.]]
15.0
4
[[ 3.  2.  0.  0.]
 [ 1.  3.  2.  0.]
 [ 0.  1.  3.  2.]
 [ 0.  0.  1.  3.]]
[[ 1.  2.  0.]
 [ 0.  3.  2.]
 [ 0.  1.  3.]]
31.0
5
[[ 3.  2.  0.  0.  0.]
 [ 1.  3.  2.  0.  0.]
 [ 0.  1.  3.  2.  0.]
 [ 0.  0.  1.  3.  2.]
 [ 0.  0.  0.  1.  3.]]
[[ 1.  2.  0.  0.]
 [ 0.  3.  2.  0.]
 [ 0.  1.  3.  2.]
 [ 0.  0.  1.  3.]]
63.0


How fast do the determinants grow?  
At rate of 2^n. 

Correct  

In [50]:
a = np.matrix([
    [3,-2],
    [1,0],
])
u = np.matrix([3,1]).T
e = linear.eigen2x2(a)
print(e)
s = linear.eigenVectors(a, e)
print(s)
print(s.I)
for r in range(8):
    print(r, s @ linear.diagonal(e, r) @ s.I @ u)

[ 2.  1.]
2.0 [[ 2.  1.]] [[ 4.  2.]] [[ 4.  2.]]
1.0 [[ 1.  1.]] [[ 1.  1.]] [[ 1.  1.]]
[[ 2.  1.]
 [ 1.  1.]]
[[ 1. -1.]
 [-1.  2.]]
0 [[ 3.]
 [ 1.]]
1 [[ 7.]
 [ 3.]]
2 [[ 15.]
 [  7.]]
3 [[ 31.]
 [ 15.]]
4 [[ 63.]
 [ 31.]]
5 [[ 127.]
 [  63.]]
6 [[ 255.]
 [ 127.]]
7 [[ 511.]
 [ 255.]]
