In [1]:
import linear, numpy as np

In [2]:
a = np.matrix([0,1,0]).T
ata = a.T @ a
aat = a @ a.T
print(linear.det(ata))
print(linear.det(aat)) # Determinant is not the same
print(ata.I) # True
print(aat) # Not positive definite 

[[ 1.]]
1.0
[[ 0.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
-0.0
[[ 1.]]
[[0 0 0]
 [0 1 0]
 [0 0 0]]


# Recitation
Eigenvalues = 1,2  
Pivots = 1,1  
Find other l and d  
l = -1 (trace) => det = product(eigenValues) = -2 = product(pivots) = 1\*1\*d => d = -2

What is the smallest a33 that would make A positive semi-definite?  
2, so that d = 0. L will be 1. 

What is the smallest c so that A+cI is positive semi-definite?  
1, so that eigenvalues are 2, 3, 0, and determinant = 0

In [3]:
a = np.matrix([
    [1,0,1],
    [0,1,1],
    [1,1,0],
])
print(linear.det(a))
aa = linear.rref(a)[-1]
e = [-1,1,2]
_ = linear.eigenVectors(a, e)

[[ 1.  0.  1.]
 [ 0.  1.  1.]
 [ 0.  0. -2.]]
-2.0
Bottom half
[[ 1.  0.  1.]
 [ 0.  1.  1.]
 [ 1.  1.  0.]]
[[ 1.  0.  1.]
 [ 0.  1.  1.]
 [ 0.  1. -1.]]
[[ 1.  0.  1.]
 [ 0.  1.  1.]
 [ 0.  0. -2.]]
Top Half
[[ 1.  0.  1.]
 [ 0.  1.  1.]
 [-0. -0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
-1 [[-0.5 -0.5  1. ]] [[ 0.5  0.5 -1. ]] [[ 0.5  0.5 -1. ]]
1 [[-1.  1. -0.]] [[-1.  1.  0.]] [[-1.  1.  0.]]
2 [[ 1.  1.  1.]] [[ 2.  2.  2.]] [[ 2.  2.  2.]]


What is limit behavior of k => infinity on uk=A^k u?  
L = [-0.5, 0.5, 1], L^infinity = [0,0,1]  
It's 1, 1, 1 for all. 

In [5]:
u = np.matrix([
    [3,0,0],
    [0,3,0],
    [0,0,3],
])
a2 = a/2
print(a2)
e2 = [-0.5, 0.5, 1]
s2 = linear.eigenVectors(a2, e2)
print(s2 @ linear.diagonal([0,0,1]) @ s2.I)

[[ 0.5  0.   0.5]
 [ 0.   0.5  0.5]
 [ 0.5  0.5  0. ]]
-0.5 [[-0.5 -0.5  1. ]] [[ 0.25  0.25 -0.5 ]] [[ 0.25  0.25 -0.5 ]]
0.5 [[-1.  1. -0.]] [[-0.5  0.5  0. ]] [[-0.5  0.5  0. ]]
1 [[ 1.  1.  1.]] [[ 1.  1.  1.]] [[ 1.  1.  1.]]
[[ 0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]
